
package com.resumeparsing.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ParsingServiceSoap", targetNamespace = "http://services.resumeparsing.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ParsingServiceSoap {


    /**
     * Parse a Resume/CV.
     * 
     * @param request
     * @return
     *     returns com.resumeparsing.services.ParseResumeResponse2
     */
    @WebMethod(operationName = "ParseResume", action = "http://services.resumeparsing.com/ParseResume")
    @WebResult(name = "ParseResumeResult", targetNamespace = "http://services.resumeparsing.com/")
    @RequestWrapper(localName = "ParseResume", targetNamespace = "http://services.resumeparsing.com/", className = "com.resumeparsing.services.ParseResume")
    @ResponseWrapper(localName = "ParseResumeResponse", targetNamespace = "http://services.resumeparsing.com/", className = "com.resumeparsing.services.ParseResumeResponse")
    public ParseResumeResponse2 parseResume(
        @WebParam(name = "request", targetNamespace = "http://services.resumeparsing.com/")
        ParseResumeRequest request);

    /**
     * Gets the Member Account information.
     * 
     * @param request
     * @return
     *     returns com.resumeparsing.services.GetAccountInfoResponse2
     */
    @WebMethod(operationName = "GetAccountInfo", action = "http://services.resumeparsing.com/GetAccountInfo")
    @WebResult(name = "GetAccountInfoResult", targetNamespace = "http://services.resumeparsing.com/")
    @RequestWrapper(localName = "GetAccountInfo", targetNamespace = "http://services.resumeparsing.com/", className = "com.resumeparsing.services.GetAccountInfo")
    @ResponseWrapper(localName = "GetAccountInfoResponse", targetNamespace = "http://services.resumeparsing.com/", className = "com.resumeparsing.services.GetAccountInfoResponse")
    public GetAccountInfoResponse2 getAccountInfo(
        @WebParam(name = "request", targetNamespace = "http://services.resumeparsing.com/")
        GetAccountInfoRequest request);

    /**
     * Parses a job order and returns the results in Sovren-defined Job Order XML format.
     * 
     * @param request
     * @return
     *     returns com.resumeparsing.services.ParseJobOrderResponse2
     */
    @WebMethod(operationName = "ParseJobOrder", action = "http://services.resumeparsing.com/ParseJobOrder")
    @WebResult(name = "ParseJobOrderResult", targetNamespace = "http://services.resumeparsing.com/")
    @RequestWrapper(localName = "ParseJobOrder", targetNamespace = "http://services.resumeparsing.com/", className = "com.resumeparsing.services.ParseJobOrder")
    @ResponseWrapper(localName = "ParseJobOrderResponse", targetNamespace = "http://services.resumeparsing.com/", className = "com.resumeparsing.services.ParseJobOrderResponse")
    public ParseJobOrderResponse2 parseJobOrder(
        @WebParam(name = "request", targetNamespace = "http://services.resumeparsing.com/")
        ParseJobOrderRequest request);

}
