package com.portal.job.dao.model;

// Generated Nov 15, 2015 11:59:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * BasicAccountDetail generated by hbm2java
 */
@Entity
@Table(name = "basic_account_detail", catalog = "jobPortal", uniqueConstraints = {
		@UniqueConstraint(columnNames = "email_id"),
		@UniqueConstraint(columnNames = "work_email_id") })
public class BasicAccountDetail implements java.io.Serializable {

	private Long accountId;
	private String emailId;
	private String workEmailId;
	private String passwordHash;
	private String forgotPasswordKey;
	private Date forgotPasswordKeyGenerateTime;
	private byte isJobseeker;
	private byte isRecruiter;
	private byte isExpert;
	private String jobseekerVerificationKey;
	private String recruiterVerificationKey;
	private String expertVerificationKey;
	private Date createDate;
	private Date modeifiedDate;
	private String emailidVerificationKey;
	private String workEmailidVerificationKey;
	private byte isEmailidVerified;
	private byte isWorkEmailidVerified;
	private String newUnverifiedEmailId;
	private String newUnverfiedWorkEmailId;
	private Set<UserDetail> userDetails = new HashSet<UserDetail>(0);

	public BasicAccountDetail() {
	}

	public BasicAccountDetail(String passwordHash, byte isJobseeker,
			byte isRecruiter, byte isExpert, Date createDate,
			Date modeifiedDate, byte isEmailidVerified,
			byte isWorkEmailidVerified) {
		this.passwordHash = passwordHash;
		this.isJobseeker = isJobseeker;
		this.isRecruiter = isRecruiter;
		this.isExpert = isExpert;
		this.createDate = createDate;
		this.modeifiedDate = modeifiedDate;
		this.isEmailidVerified = isEmailidVerified;
		this.isWorkEmailidVerified = isWorkEmailidVerified;
	}

	public BasicAccountDetail(String emailId, String workEmailId,
			String passwordHash, String forgotPasswordKey,
			Date forgotPasswordKeyGenerateTime, byte isJobseeker,
			byte isRecruiter, byte isExpert, String jobseekerVerificationKey,
			String recruiterVerificationKey, String expertVerificationKey,
			Date createDate, Date modeifiedDate, String emailidVerificationKey,
			String workEmailidVerificationKey, byte isEmailidVerified,
			byte isWorkEmailidVerified, String newUnverifiedEmailId,
			String newUnverfiedWorkEmailId, Set<UserDetail> userDetails) {
		this.emailId = emailId;
		this.workEmailId = workEmailId;
		this.passwordHash = passwordHash;
		this.forgotPasswordKey = forgotPasswordKey;
		this.forgotPasswordKeyGenerateTime = forgotPasswordKeyGenerateTime;
		this.isJobseeker = isJobseeker;
		this.isRecruiter = isRecruiter;
		this.isExpert = isExpert;
		this.jobseekerVerificationKey = jobseekerVerificationKey;
		this.recruiterVerificationKey = recruiterVerificationKey;
		this.expertVerificationKey = expertVerificationKey;
		this.createDate = createDate;
		this.modeifiedDate = modeifiedDate;
		this.emailidVerificationKey = emailidVerificationKey;
		this.workEmailidVerificationKey = workEmailidVerificationKey;
		this.isEmailidVerified = isEmailidVerified;
		this.isWorkEmailidVerified = isWorkEmailidVerified;
		this.newUnverifiedEmailId = newUnverifiedEmailId;
		this.newUnverfiedWorkEmailId = newUnverfiedWorkEmailId;
		this.userDetails = userDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "account_id", unique = true, nullable = false)
	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	@Column(name = "email_id", unique = true, length = 200)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "work_email_id", unique = true, length = 200)
	public String getWorkEmailId() {
		return this.workEmailId;
	}

	public void setWorkEmailId(String workEmailId) {
		this.workEmailId = workEmailId;
	}

	@Column(name = "password_hash", nullable = false, length = 65535)
	public String getPasswordHash() {
		return this.passwordHash;
	}

	public void setPasswordHash(String passwordHash) {
		this.passwordHash = passwordHash;
	}

	@Column(name = "forgot_password_key", length = 65535)
	public String getForgotPasswordKey() {
		return this.forgotPasswordKey;
	}

	public void setForgotPasswordKey(String forgotPasswordKey) {
		this.forgotPasswordKey = forgotPasswordKey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "forgot_password_key_generate_time", length = 19)
	public Date getForgotPasswordKeyGenerateTime() {
		return this.forgotPasswordKeyGenerateTime;
	}

	public void setForgotPasswordKeyGenerateTime(
			Date forgotPasswordKeyGenerateTime) {
		this.forgotPasswordKeyGenerateTime = forgotPasswordKeyGenerateTime;
	}

	@Column(name = "is_jobseeker", nullable = false)
	public byte getIsJobseeker() {
		return this.isJobseeker;
	}

	public void setIsJobseeker(byte isJobseeker) {
		this.isJobseeker = isJobseeker;
	}

	@Column(name = "is_recruiter", nullable = false)
	public byte getIsRecruiter() {
		return this.isRecruiter;
	}

	public void setIsRecruiter(byte isRecruiter) {
		this.isRecruiter = isRecruiter;
	}

	@Column(name = "is_expert", nullable = false)
	public byte getIsExpert() {
		return this.isExpert;
	}

	public void setIsExpert(byte isExpert) {
		this.isExpert = isExpert;
	}

	@Column(name = "jobseeker_verification_key", length = 65535)
	public String getJobseekerVerificationKey() {
		return this.jobseekerVerificationKey;
	}

	public void setJobseekerVerificationKey(String jobseekerVerificationKey) {
		this.jobseekerVerificationKey = jobseekerVerificationKey;
	}

	@Column(name = "recruiter_verification_key", length = 65535)
	public String getRecruiterVerificationKey() {
		return this.recruiterVerificationKey;
	}

	public void setRecruiterVerificationKey(String recruiterVerificationKey) {
		this.recruiterVerificationKey = recruiterVerificationKey;
	}

	@Column(name = "expert_verification_key", length = 65535)
	public String getExpertVerificationKey() {
		return this.expertVerificationKey;
	}

	public void setExpertVerificationKey(String expertVerificationKey) {
		this.expertVerificationKey = expertVerificationKey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modeified_date", nullable = false, length = 19)
	public Date getModeifiedDate() {
		return this.modeifiedDate;
	}

	public void setModeifiedDate(Date modeifiedDate) {
		this.modeifiedDate = modeifiedDate;
	}

	@Column(name = "emailid_verification_key", length = 65535)
	public String getEmailidVerificationKey() {
		return this.emailidVerificationKey;
	}

	public void setEmailidVerificationKey(String emailidVerificationKey) {
		this.emailidVerificationKey = emailidVerificationKey;
	}

	@Column(name = "work_emailid_verification_key", length = 65535)
	public String getWorkEmailidVerificationKey() {
		return this.workEmailidVerificationKey;
	}

	public void setWorkEmailidVerificationKey(String workEmailidVerificationKey) {
		this.workEmailidVerificationKey = workEmailidVerificationKey;
	}

	@Column(name = "is_emailid_verified", nullable = false)
	public byte getIsEmailidVerified() {
		return this.isEmailidVerified;
	}

	public void setIsEmailidVerified(byte isEmailidVerified) {
		this.isEmailidVerified = isEmailidVerified;
	}

	@Column(name = "is_work_emailid_verified", nullable = false)
	public byte getIsWorkEmailidVerified() {
		return this.isWorkEmailidVerified;
	}

	public void setIsWorkEmailidVerified(byte isWorkEmailidVerified) {
		this.isWorkEmailidVerified = isWorkEmailidVerified;
	}

	@Column(name = "new_unverified_email_id", length = 200)
	public String getNewUnverifiedEmailId() {
		return this.newUnverifiedEmailId;
	}

	public void setNewUnverifiedEmailId(String newUnverifiedEmailId) {
		this.newUnverifiedEmailId = newUnverifiedEmailId;
	}

	@Column(name = "new_unverfied_work_email_id", length = 200)
	public String getNewUnverfiedWorkEmailId() {
		return this.newUnverfiedWorkEmailId;
	}

	public void setNewUnverfiedWorkEmailId(String newUnverfiedWorkEmailId) {
		this.newUnverfiedWorkEmailId = newUnverfiedWorkEmailId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "basicAccountDetail")
	public Set<UserDetail> getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(Set<UserDetail> userDetails) {
		this.userDetails = userDetails;
	}

}
