package com.portal.job.dao.model;

// Generated Nov 15, 2015 11:59:15 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * IndustryCodeDetail generated by hbm2java
 */
@Entity
@Table(name = "industry_code_detail", catalog = "jobPortal", uniqueConstraints = @UniqueConstraint(columnNames = "industry_description"))
public class IndustryCodeDetail implements java.io.Serializable {

	private int industryCode;
	private String industryDescription;
	private Set<OrganisationDetail> organisationDetails = new HashSet<OrganisationDetail>(
			0);

	public IndustryCodeDetail() {
	}

	public IndustryCodeDetail(int industryCode, String industryDescription) {
		this.industryCode = industryCode;
		this.industryDescription = industryDescription;
	}

	public IndustryCodeDetail(int industryCode, String industryDescription,
			Set<OrganisationDetail> organisationDetails) {
		this.industryCode = industryCode;
		this.industryDescription = industryDescription;
		this.organisationDetails = organisationDetails;
	}

	@Id
	@Column(name = "industry_code", unique = true, nullable = false)
	public int getIndustryCode() {
		return this.industryCode;
	}

	public void setIndustryCode(int industryCode) {
		this.industryCode = industryCode;
	}

	@Column(name = "industry_description", unique = true, nullable = false, length = 200)
	public String getIndustryDescription() {
		return this.industryDescription;
	}

	public void setIndustryDescription(String industryDescription) {
		this.industryDescription = industryDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "industryCodeDetail")
	public Set<OrganisationDetail> getOrganisationDetails() {
		return this.organisationDetails;
	}

	public void setOrganisationDetails(
			Set<OrganisationDetail> organisationDetails) {
		this.organisationDetails = organisationDetails;
	}

}
