package com.portal.job.dao.model;

// Generated Nov 15, 2015 11:59:15 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * JobsByUser generated by hbm2java
 */
@Entity
@Table(name = "jobs_by_user", catalog = "jobPortal", uniqueConstraints = @UniqueConstraint(columnNames = {
		"job_id", "user_id" }))
public class JobsByUser implements java.io.Serializable {

	private Long jobByUserId;
	private JobDetail jobDetail;
	private UserDetail userDetail;
	private long percentageMatch;

	public JobsByUser() {
	}

	public JobsByUser(JobDetail jobDetail, UserDetail userDetail,
			long percentageMatch) {
		this.jobDetail = jobDetail;
		this.userDetail = userDetail;
		this.percentageMatch = percentageMatch;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "job_by_user_id", unique = true, nullable = false)
	public Long getJobByUserId() {
		return this.jobByUserId;
	}

	public void setJobByUserId(Long jobByUserId) {
		this.jobByUserId = jobByUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "job_id", nullable = false)
	public JobDetail getJobDetail() {
		return this.jobDetail;
	}

	public void setJobDetail(JobDetail jobDetail) {
		this.jobDetail = jobDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public UserDetail getUserDetail() {
		return this.userDetail;
	}

	public void setUserDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	@Column(name = "percentage_match", nullable = false)
	public long getPercentageMatch() {
		return this.percentageMatch;
	}

	public void setPercentageMatch(long percentageMatch) {
		this.percentageMatch = percentageMatch;
	}

}
