package com.portal.job.dao.model;

// Generated Nov 15, 2015 11:59:15 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * OrganisationDetail generated by hbm2java
 */
@Entity
@Table(name = "organisation_detail", catalog = "jobPortal", uniqueConstraints = @UniqueConstraint(columnNames = "organisation_name"))
public class OrganisationDetail implements java.io.Serializable {

	private Long organisationId;
	private IndustryCodeDetail industryCodeDetail;
	private String organisationName;
	private Integer organisationTier;

	public OrganisationDetail() {
	}

	public OrganisationDetail(IndustryCodeDetail industryCodeDetail,
			String organisationName) {
		this.industryCodeDetail = industryCodeDetail;
		this.organisationName = organisationName;
	}

	public OrganisationDetail(IndustryCodeDetail industryCodeDetail,
			String organisationName, Integer organisationTier) {
		this.industryCodeDetail = industryCodeDetail;
		this.organisationName = organisationName;
		this.organisationTier = organisationTier;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "organisation_id", unique = true, nullable = false)
	public Long getOrganisationId() {
		return this.organisationId;
	}

	public void setOrganisationId(Long organisationId) {
		this.organisationId = organisationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "organisastion_industry_code", nullable = false)
	public IndustryCodeDetail getIndustryCodeDetail() {
		return this.industryCodeDetail;
	}

	public void setIndustryCodeDetail(IndustryCodeDetail industryCodeDetail) {
		this.industryCodeDetail = industryCodeDetail;
	}

	@Column(name = "organisation_name", unique = true, nullable = false, length = 200)
	public String getOrganisationName() {
		return this.organisationName;
	}

	public void setOrganisationName(String organisationName) {
		this.organisationName = organisationName;
	}

	@Column(name = "organisation_tier")
	public Integer getOrganisationTier() {
		return this.organisationTier;
	}

	public void setOrganisationTier(Integer organisationTier) {
		this.organisationTier = organisationTier;
	}

}
