package com.portal.job.dao.model;

// Generated Nov 15, 2015 11:59:15 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RequestDemoDetail generated by hbm2java
 */
@Entity
@Table(name = "request_demo_detail", catalog = "jobPortal", uniqueConstraints = @UniqueConstraint(columnNames = "email_id"))
public class RequestDemoDetail implements java.io.Serializable {

	private Long id;
	private String name;
	private String companyName;
	private String emailId;
	private String mobileNumber;

	public RequestDemoDetail() {
	}

	public RequestDemoDetail(String name, String companyName, String emailId,
			String mobileNumber) {
		this.name = name;
		this.companyName = companyName;
		this.emailId = emailId;
		this.mobileNumber = mobileNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "company_name", nullable = false, length = 200)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "email_id", unique = true, nullable = false, length = 200)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "mobile_number", nullable = false, length = 20)
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

}
