package com.portal.job.dao.model;

// Generated Nov 15, 2015 11:59:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserAwardDetail generated by hbm2java
 */
@Entity
@Table(name = "user_award_detail", catalog = "jobPortal")
public class UserAwardDetail implements java.io.Serializable {

	private Long awardId;
	private UserDetail userDetail;
	private String title;
	private String organisationName;
	private Date date;

	public UserAwardDetail() {
	}

	public UserAwardDetail(UserDetail userDetail, String title) {
		this.userDetail = userDetail;
		this.title = title;
	}

	public UserAwardDetail(UserDetail userDetail, String title,
			String organisationName, Date date) {
		this.userDetail = userDetail;
		this.title = title;
		this.organisationName = organisationName;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "award_id", unique = true, nullable = false)
	public Long getAwardId() {
		return this.awardId;
	}

	public void setAwardId(Long awardId) {
		this.awardId = awardId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public UserDetail getUserDetail() {
		return this.userDetail;
	}

	public void setUserDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	@Column(name = "title", nullable = false, length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "organisation_name", length = 65535)
	public String getOrganisationName() {
		return this.organisationName;
	}

	public void setOrganisationName(String organisationName) {
		this.organisationName = organisationName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
