package com.portal.job.dao.model;

// Generated Nov 15, 2015 11:59:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserCertificationDetail generated by hbm2java
 */
@Entity
@Table(name = "user_certification_detail", catalog = "jobPortal")
public class UserCertificationDetail implements java.io.Serializable {

	private Long certificationId;
	private UserDetail userDetail;
	private String name;
	private String organisationName;
	private String url;
	private Date startDate;
	private Date endDate;

	public UserCertificationDetail() {
	}

	public UserCertificationDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	public UserCertificationDetail(UserDetail userDetail, String name,
			String organisationName, String url, Date startDate, Date endDate) {
		this.userDetail = userDetail;
		this.name = name;
		this.organisationName = organisationName;
		this.url = url;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "certification_id", unique = true, nullable = false)
	public Long getCertificationId() {
		return this.certificationId;
	}

	public void setCertificationId(Long certificationId) {
		this.certificationId = certificationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public UserDetail getUserDetail() {
		return this.userDetail;
	}

	public void setUserDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	@Column(name = "name", length = 65535)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "organisation_name", length = 65535)
	public String getOrganisationName() {
		return this.organisationName;
	}

	public void setOrganisationName(String organisationName) {
		this.organisationName = organisationName;
	}

	@Column(name = "url", length = 65535)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
