package com.portal.job.dao.model;

// Generated Nov 15, 2015 11:59:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserProjectDetail generated by hbm2java
 */
@Entity
@Table(name = "user_project_detail", catalog = "jobPortal")
public class UserProjectDetail implements java.io.Serializable {

	private Long projectId;
	private UserDetail userDetail;
	private String projectName;
	private Date projectDate;
	private String projectUrl;
	private String projectDescription;

	public UserProjectDetail() {
	}

	public UserProjectDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	public UserProjectDetail(UserDetail userDetail, String projectName,
			Date projectDate, String projectUrl, String projectDescription) {
		this.userDetail = userDetail;
		this.projectName = projectName;
		this.projectDate = projectDate;
		this.projectUrl = projectUrl;
		this.projectDescription = projectDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "project_id", unique = true, nullable = false)
	public Long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public UserDetail getUserDetail() {
		return this.userDetail;
	}

	public void setUserDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	@Column(name = "project_name", length = 65535)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "project_date", length = 10)
	public Date getProjectDate() {
		return this.projectDate;
	}

	public void setProjectDate(Date projectDate) {
		this.projectDate = projectDate;
	}

	@Column(name = "project_url", length = 65535)
	public String getProjectUrl() {
		return this.projectUrl;
	}

	public void setProjectUrl(String projectUrl) {
		this.projectUrl = projectUrl;
	}

	@Column(name = "project_description", length = 65535)
	public String getProjectDescription() {
		return this.projectDescription;
	}

	public void setProjectDescription(String projectDescription) {
		this.projectDescription = projectDescription;
	}

}
