package com.portal.job.dao.model;

// Generated Nov 15, 2015 11:59:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserVolunteerDetail generated by hbm2java
 */
@Entity
@Table(name = "user_volunteer_detail", catalog = "jobPortal")
public class UserVolunteerDetail implements java.io.Serializable {

	private Long volunteerId;
	private UserDetail userDetail;
	private String roleName;
	private String organisationName;
	private String causeName;
	private Date startDate;
	private Date endDate;
	private String description;

	public UserVolunteerDetail() {
	}

	public UserVolunteerDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	public UserVolunteerDetail(UserDetail userDetail, String roleName,
			String organisationName, String causeName, Date startDate,
			Date endDate, String description) {
		this.userDetail = userDetail;
		this.roleName = roleName;
		this.organisationName = organisationName;
		this.causeName = causeName;
		this.startDate = startDate;
		this.endDate = endDate;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "volunteer_id", unique = true, nullable = false)
	public Long getVolunteerId() {
		return this.volunteerId;
	}

	public void setVolunteerId(Long volunteerId) {
		this.volunteerId = volunteerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public UserDetail getUserDetail() {
		return this.userDetail;
	}

	public void setUserDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	@Column(name = "role_name", length = 65535)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "organisation_name", length = 65535)
	public String getOrganisationName() {
		return this.organisationName;
	}

	public void setOrganisationName(String organisationName) {
		this.organisationName = organisationName;
	}

	@Column(name = "cause_name", length = 65535)
	public String getCauseName() {
		return this.causeName;
	}

	public void setCauseName(String causeName) {
		this.causeName = causeName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
