package com.portal.job.dao.model;

// Generated Nov 15, 2015 11:59:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserPatentDetail generated by hbm2java
 */
@Entity
@Table(name = "user_patent_detail", catalog = "jobPortal")
public class UserPatentDetail implements java.io.Serializable {

	private Long patentId;
	private UserDetail userDetail;
	private String title;
	private String countryCode;
	private String patentStatus;
	private String applicationNumber;
	private Date filingDate;
	private String url;
	private String description;

	public UserPatentDetail() {
	}

	public UserPatentDetail(UserDetail userDetail, String title) {
		this.userDetail = userDetail;
		this.title = title;
	}

	public UserPatentDetail(UserDetail userDetail, String title,
			String countryCode, String patentStatus, String applicationNumber,
			Date filingDate, String url, String description) {
		this.userDetail = userDetail;
		this.title = title;
		this.countryCode = countryCode;
		this.patentStatus = patentStatus;
		this.applicationNumber = applicationNumber;
		this.filingDate = filingDate;
		this.url = url;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "patent_id", unique = true, nullable = false)
	public Long getPatentId() {
		return this.patentId;
	}

	public void setPatentId(Long patentId) {
		this.patentId = patentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public UserDetail getUserDetail() {
		return this.userDetail;
	}

	public void setUserDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	@Column(name = "title", nullable = false, length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "country_code", length = 65535)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "patent_status", length = 65535)
	public String getPatentStatus() {
		return this.patentStatus;
	}

	public void setPatentStatus(String patentStatus) {
		this.patentStatus = patentStatus;
	}

	@Column(name = "application_number", length = 65535)
	public String getApplicationNumber() {
		return this.applicationNumber;
	}

	public void setApplicationNumber(String applicationNumber) {
		this.applicationNumber = applicationNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "filing_date", length = 10)
	public Date getFilingDate() {
		return this.filingDate;
	}

	public void setFilingDate(Date filingDate) {
		this.filingDate = filingDate;
	}

	@Column(name = "url", length = 65535)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
