package com.portal.job.dao.model;

// Generated Nov 15, 2015 11:59:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserPublicationDetail generated by hbm2java
 */
@Entity
@Table(name = "user_publication_detail", catalog = "jobPortal")
public class UserPublicationDetail implements java.io.Serializable {

	private Long publicationId;
	private UserDetail userDetail;
	private String title;
	private String publicationOrganisation;
	private Date date;
	private String description;

	public UserPublicationDetail() {
	}

	public UserPublicationDetail(UserDetail userDetail, String title) {
		this.userDetail = userDetail;
		this.title = title;
	}

	public UserPublicationDetail(UserDetail userDetail, String title,
			String publicationOrganisation, Date date, String description) {
		this.userDetail = userDetail;
		this.title = title;
		this.publicationOrganisation = publicationOrganisation;
		this.date = date;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "publication_id", unique = true, nullable = false)
	public Long getPublicationId() {
		return this.publicationId;
	}

	public void setPublicationId(Long publicationId) {
		this.publicationId = publicationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public UserDetail getUserDetail() {
		return this.userDetail;
	}

	public void setUserDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	@Column(name = "title", nullable = false, length = 65535)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "publication_organisation", length = 65535)
	public String getPublicationOrganisation() {
		return this.publicationOrganisation;
	}

	public void setPublicationOrganisation(String publicationOrganisation) {
		this.publicationOrganisation = publicationOrganisation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
