package com.portal.job.dao.model;

// Generated Nov 15, 2015 11:59:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserTestDetail generated by hbm2java
 */
@Entity
@Table(name = "user_test_detail", catalog = "jobPortal")
public class UserTestDetail implements java.io.Serializable {

	private Long testId;
	private UserDetail userDetail;
	private String testName;
	private String testScore;
	private Date testDate;
	private String testDescription;

	public UserTestDetail() {
	}

	public UserTestDetail(UserDetail userDetail, String testName,
			String testScore) {
		this.userDetail = userDetail;
		this.testName = testName;
		this.testScore = testScore;
	}

	public UserTestDetail(UserDetail userDetail, String testName,
			String testScore, Date testDate, String testDescription) {
		this.userDetail = userDetail;
		this.testName = testName;
		this.testScore = testScore;
		this.testDate = testDate;
		this.testDescription = testDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "test_id", unique = true, nullable = false)
	public Long getTestId() {
		return this.testId;
	}

	public void setTestId(Long testId) {
		this.testId = testId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public UserDetail getUserDetail() {
		return this.userDetail;
	}

	public void setUserDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	@Column(name = "test_name", nullable = false, length = 100)
	public String getTestName() {
		return this.testName;
	}

	public void setTestName(String testName) {
		this.testName = testName;
	}

	@Column(name = "test_score", nullable = false, length = 10)
	public String getTestScore() {
		return this.testScore;
	}

	public void setTestScore(String testScore) {
		this.testScore = testScore;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "test_date", length = 10)
	public Date getTestDate() {
		return this.testDate;
	}

	public void setTestDate(Date testDate) {
		this.testDate = testDate;
	}

	@Column(name = "test_description", length = 65535)
	public String getTestDescription() {
		return this.testDescription;
	}

	public void setTestDescription(String testDescription) {
		this.testDescription = testDescription;
	}

}
