package com.portal.job.dao.model;

// Generated Nov 15, 2015 11:59:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserExperinceDetail generated by hbm2java
 */
@Entity
@Table(name = "user_experince_detail", catalog = "jobPortal")
public class UserExperinceDetail implements java.io.Serializable {

	private Long experinceId;
	private UserDetail userDetail;
	private String companyName;
	private String roleName;
	private Date timePeriodStart;
	private Date timePeriodEnd;
	private String description;
	private String locationDetail;
	private Byte isCurrentJob;
	private Integer organisationTier;
	private Integer totalExpMonth;

	public UserExperinceDetail() {
	}

	public UserExperinceDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	public UserExperinceDetail(UserDetail userDetail, String companyName,
			String roleName, Date timePeriodStart, Date timePeriodEnd,
			String description, String locationDetail, Byte isCurrentJob,
			Integer organisationTier, Integer totalExpMonth) {
		this.userDetail = userDetail;
		this.companyName = companyName;
		this.roleName = roleName;
		this.timePeriodStart = timePeriodStart;
		this.timePeriodEnd = timePeriodEnd;
		this.description = description;
		this.locationDetail = locationDetail;
		this.isCurrentJob = isCurrentJob;
		this.organisationTier = organisationTier;
		this.totalExpMonth = totalExpMonth;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "experince_id", unique = true, nullable = false)
	public Long getExperinceId() {
		return this.experinceId;
	}

	public void setExperinceId(Long experinceId) {
		this.experinceId = experinceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public UserDetail getUserDetail() {
		return this.userDetail;
	}

	public void setUserDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	@Column(name = "company_name", length = 65535)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "role_name", length = 65535)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "time_period_start", length = 10)
	public Date getTimePeriodStart() {
		return this.timePeriodStart;
	}

	public void setTimePeriodStart(Date timePeriodStart) {
		this.timePeriodStart = timePeriodStart;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "time_period_end", length = 10)
	public Date getTimePeriodEnd() {
		return this.timePeriodEnd;
	}

	public void setTimePeriodEnd(Date timePeriodEnd) {
		this.timePeriodEnd = timePeriodEnd;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "location_detail", length = 65535)
	public String getLocationDetail() {
		return this.locationDetail;
	}

	public void setLocationDetail(String locationDetail) {
		this.locationDetail = locationDetail;
	}

	@Column(name = "is_current_job")
	public Byte getIsCurrentJob() {
		return this.isCurrentJob;
	}

	public void setIsCurrentJob(Byte isCurrentJob) {
		this.isCurrentJob = isCurrentJob;
	}

	@Column(name = "organisation_tier")
	public Integer getOrganisationTier() {
		return this.organisationTier;
	}

	public void setOrganisationTier(Integer organisationTier) {
		this.organisationTier = organisationTier;
	}

	@Column(name = "total_exp_month")
	public Integer getTotalExpMonth() {
		return this.totalExpMonth;
	}

	public void setTotalExpMonth(Integer totalExpMonth) {
		this.totalExpMonth = totalExpMonth;
	}

}
