package com.portal.job.dao.model;

// Generated Nov 15, 2015 11:59:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserEducationDetail generated by hbm2java
 */
@Entity
@Table(name = "user_education_detail", catalog = "jobPortal")
public class UserEducationDetail implements java.io.Serializable {

	private Long educationId;
	private UserDetail userDetail;
	private String educationalOrg;
	private Date timePeriodStart;
	private Date timePeriodEnd;
	private String degree;
	private String majorSubject;
	private String description;
	private Integer organisationTier;
	private String degreeType;

	public UserEducationDetail() {
	}

	public UserEducationDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	public UserEducationDetail(UserDetail userDetail, String educationalOrg,
			Date timePeriodStart, Date timePeriodEnd, String degree,
			String majorSubject, String description, Integer organisationTier,
			String degreeType) {
		this.userDetail = userDetail;
		this.educationalOrg = educationalOrg;
		this.timePeriodStart = timePeriodStart;
		this.timePeriodEnd = timePeriodEnd;
		this.degree = degree;
		this.majorSubject = majorSubject;
		this.description = description;
		this.organisationTier = organisationTier;
		this.degreeType = degreeType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "education_id", unique = true, nullable = false)
	public Long getEducationId() {
		return this.educationId;
	}

	public void setEducationId(Long educationId) {
		this.educationId = educationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public UserDetail getUserDetail() {
		return this.userDetail;
	}

	public void setUserDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	@Column(name = "educational_org", length = 65535)
	public String getEducationalOrg() {
		return this.educationalOrg;
	}

	public void setEducationalOrg(String educationalOrg) {
		this.educationalOrg = educationalOrg;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "time_period_start", length = 10)
	public Date getTimePeriodStart() {
		return this.timePeriodStart;
	}

	public void setTimePeriodStart(Date timePeriodStart) {
		this.timePeriodStart = timePeriodStart;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "time_period_end", length = 10)
	public Date getTimePeriodEnd() {
		return this.timePeriodEnd;
	}

	public void setTimePeriodEnd(Date timePeriodEnd) {
		this.timePeriodEnd = timePeriodEnd;
	}

	@Column(name = "degree", length = 65535)
	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	@Column(name = "major_subject", length = 65535)
	public String getMajorSubject() {
		return this.majorSubject;
	}

	public void setMajorSubject(String majorSubject) {
		this.majorSubject = majorSubject;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "organisation_tier")
	public Integer getOrganisationTier() {
		return this.organisationTier;
	}

	public void setOrganisationTier(Integer organisationTier) {
		this.organisationTier = organisationTier;
	}

	@Column(name = "degree_type", length = 200)
	public String getDegreeType() {
		return this.degreeType;
	}

	public void setDegreeType(String degreeType) {
		this.degreeType = degreeType;
	}

}
