INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('product manager','product manager');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('product management','product manager');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('director of product','product manager');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('head of product','product manager');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('big data architect','big data');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('hadoop developer','big data');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('big data engineer','big data');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('hadoop administrator','big data');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('business analysis','business analysis');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('business analyst','business analysis');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('market research','business analysis');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('strategy','business analysis');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('business strategy','business analysis');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('technology strategist','business analysis');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('business analysis','business analysis');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('business strategy','business analysis');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('business management','business analysis');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('quantitative modeling','data analysis');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('quantitative development','data analysis');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('data visualization','data analysis');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('tableau','data analysis');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('statistical modeling','data analysis');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('data analyst','data analysis');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('data analytics','data analysis');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('data analysis','data analysis');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('business analytics','data analysis');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('business intelligence','data analysis');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('quantitative','data analysis');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('data engineer','data engineering');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('data architect','data engineering');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('etl architect','data engineering');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('etl engineer','data engineering');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('data munging','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('data products','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('apache mahout','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('recommender systems','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('data science','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('web scraping','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('web crawling','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('text mining','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('natural language processing','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('predictive analytics','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('predictive modeling','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('machine learning','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('data analytics','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('text classification','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('text analysis','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('statistical machine translation','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('computational semantics','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('web mining','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('semantic search','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('lexical semantics','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('information retrieval','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('image processing','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('convex optimization','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('bayesian networks','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('anomaly detection','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('social network analytics','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('probabilistic models','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('data scientist','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('data science','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('data mining','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('data science','data science');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('natural language processing','natural language processing');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('sentiment analysis','natural language processing');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('computational linguistics','natural language processing');
INSERT INTO jobPortal.role_detail(role_name,role_desc) VALUES ('semantic analysis','natural language processing');