//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//
package com.portal.job.resumeparsing.xmlparsing.userArea.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BestFitTaxonomyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BestFitTaxonomyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BestFitTaxonomy" type="{http://sovren.com/hr-xml/2006-02-28}BestFitTaxonomyType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="rootId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="weight" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="percentOfOverall" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="percentOfParent" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BestFitTaxonomyType", propOrder = {
    "bestFitTaxonomy"
})
public class BestFitTaxonomyType {

    @XmlElement(name = "BestFitTaxonomy")
    protected List<BestFitTaxonomyType> bestFitTaxonomy;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "rootId", required = true)
    protected String rootId;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "weight", required = true)
    protected double weight;
    @XmlAttribute(name = "percentOfOverall", required = true)
    protected double percentOfOverall;
    @XmlAttribute(name = "percentOfParent", required = true)
    protected double percentOfParent;

    /**
     * Gets the value of the bestFitTaxonomy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bestFitTaxonomy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBestFitTaxonomy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BestFitTaxonomyType }
     * 
     * 
     */
    public List<BestFitTaxonomyType> getBestFitTaxonomy() {
        if (bestFitTaxonomy == null) {
            bestFitTaxonomy = new ArrayList<BestFitTaxonomyType>();
        }
        return this.bestFitTaxonomy;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the rootId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRootId() {
        return rootId;
    }

    /**
     * Sets the value of the rootId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRootId(String value) {
        this.rootId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     */
    public double getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     */
    public void setWeight(double value) {
        this.weight = value;
    }

    /**
     * Gets the value of the percentOfOverall property.
     * 
     */
    public double getPercentOfOverall() {
        return percentOfOverall;
    }

    /**
     * Sets the value of the percentOfOverall property.
     * 
     */
    public void setPercentOfOverall(double value) {
        this.percentOfOverall = value;
    }

    /**
     * Gets the value of the percentOfParent property.
     * 
     */
    public double getPercentOfParent() {
        return percentOfParent;
    }

    /**
     * Sets the value of the percentOfParent property.
     * 
     */
    public void setPercentOfParent(double value) {
        this.percentOfParent = value;
    }

}
