//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//


package com.portal.job.resumeparsing.xmlparsing.userArea.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Graduated" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="NormalizedGPA" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="NormalizedSchoolName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NormalizedDegreeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NormalizedDegreeType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NormalizedLocation" type="{http://sovren.com/hr-xml/2006-02-28}LocationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "graduated",
    "normalizedGPA",
    "normalizedSchoolName",
    "normalizedDegreeName",
    "normalizedDegreeType",
    "normalizedLocation"
})
@XmlRootElement(name = "DegreeUserArea")
public class DegreeUserArea {

    @XmlElement(name = "Id")
    protected String id;
    @XmlElement(name = "Graduated")
    protected Boolean graduated;
    @XmlElement(name = "NormalizedGPA")
    protected BigDecimal normalizedGPA;
    @XmlElement(name = "NormalizedSchoolName")
    protected String normalizedSchoolName;
    @XmlElement(name = "NormalizedDegreeName")
    protected String normalizedDegreeName;
    @XmlElement(name = "NormalizedDegreeType")
    protected String normalizedDegreeType;
    @XmlElement(name = "NormalizedLocation")
    protected LocationType normalizedLocation;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the graduated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGraduated() {
        return graduated;
    }

    /**
     * Sets the value of the graduated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGraduated(Boolean value) {
        this.graduated = value;
    }

    /**
     * Gets the value of the normalizedGPA property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNormalizedGPA() {
        return normalizedGPA;
    }

    /**
     * Sets the value of the normalizedGPA property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNormalizedGPA(BigDecimal value) {
        this.normalizedGPA = value;
    }

    /**
     * Gets the value of the normalizedSchoolName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNormalizedSchoolName() {
        return normalizedSchoolName;
    }

    /**
     * Sets the value of the normalizedSchoolName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNormalizedSchoolName(String value) {
        this.normalizedSchoolName = value;
    }

    /**
     * Gets the value of the normalizedDegreeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNormalizedDegreeName() {
        return normalizedDegreeName;
    }

    /**
     * Sets the value of the normalizedDegreeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNormalizedDegreeName(String value) {
        this.normalizedDegreeName = value;
    }

    /**
     * Gets the value of the normalizedDegreeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNormalizedDegreeType() {
        return normalizedDegreeType;
    }

    /**
     * Sets the value of the normalizedDegreeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNormalizedDegreeType(String value) {
        this.normalizedDegreeType = value;
    }

    /**
     * Gets the value of the normalizedLocation property.
     * 
     * @return
     *     possible object is
     *     {@link LocationType }
     *     
     */
    public LocationType getNormalizedLocation() {
        return normalizedLocation;
    }

    /**
     * Sets the value of the normalizedLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationType }
     *     
     */
    public void setNormalizedLocation(LocationType value) {
        this.normalizedLocation = value;
    }

}
