//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//


package com.portal.job.resumeparsing.xmlparsing.userArea.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExecutiveTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExecutiveTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="executive"/>
 *     &lt;enumeration value="admin"/>
 *     &lt;enumeration value="accounting"/>
 *     &lt;enumeration value="operations"/>
 *     &lt;enumeration value="financial"/>
 *     &lt;enumeration value="marketing"/>
 *     &lt;enumeration value="business_dev"/>
 *     &lt;enumeration value="it"/>
 *     &lt;enumeration value="general"/>
 *     &lt;enumeration value="learning"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ExecutiveTypeEnum")
@XmlEnum
public enum ExecutiveTypeEnum {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("executive")
    EXECUTIVE("executive"),
    @XmlEnumValue("admin")
    ADMIN("admin"),
    @XmlEnumValue("accounting")
    ACCOUNTING("accounting"),
    @XmlEnumValue("operations")
    OPERATIONS("operations"),
    @XmlEnumValue("financial")
    FINANCIAL("financial"),
    @XmlEnumValue("marketing")
    MARKETING("marketing"),
    @XmlEnumValue("business_dev")
    BUSINESS_DEV("business_dev"),
    @XmlEnumValue("it")
    IT("it"),
    @XmlEnumValue("general")
    GENERAL("general"),
    @XmlEnumValue("learning")
    LEARNING("learning");
    private final String value;

    ExecutiveTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ExecutiveTypeEnum fromValue(String v) {
        for (ExecutiveTypeEnum c: ExecutiveTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
