//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//


package com.portal.job.resumeparsing.xmlparsing.userArea.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for LocationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Latitude" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://sovren.com/hr-xml/2006-02-28>LatitudeType">
 *                 &lt;attGroup ref="{http://sovren.com/hr-xml/2006-02-28}Inferred"/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Longitude" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://sovren.com/hr-xml/2006-02-28>LongitudeType">
 *                 &lt;attGroup ref="{http://sovren.com/hr-xml/2006-02-28}Inferred"/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="NormalizedStreetAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NormalizedMunicipality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NormalizedRegion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NormalizedPostalCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NormalizedCountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocationType", propOrder = {
    "latitude",
    "longitude",
    "normalizedStreetAddress",
    "normalizedMunicipality",
    "normalizedRegion",
    "normalizedPostalCode",
    "normalizedCountryCode"
})
public class LocationType {

    @XmlElement(name = "Latitude")
    protected LocationType.Latitude latitude;
    @XmlElement(name = "Longitude")
    protected LocationType.Longitude longitude;
    @XmlElement(name = "NormalizedStreetAddress")
    protected String normalizedStreetAddress;
    @XmlElement(name = "NormalizedMunicipality")
    protected String normalizedMunicipality;
    @XmlElement(name = "NormalizedRegion")
    protected String normalizedRegion;
    @XmlElement(name = "NormalizedPostalCode")
    protected String normalizedPostalCode;
    @XmlElement(name = "NormalizedCountryCode")
    protected String normalizedCountryCode;

    /**
     * Gets the value of the latitude property.
     * 
     * @return
     *     possible object is
     *     {@link LocationType.Latitude }
     *     
     */
    public LocationType.Latitude getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationType.Latitude }
     *     
     */
    public void setLatitude(LocationType.Latitude value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return
     *     possible object is
     *     {@link LocationType.Longitude }
     *     
     */
    public LocationType.Longitude getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationType.Longitude }
     *     
     */
    public void setLongitude(LocationType.Longitude value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the normalizedStreetAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNormalizedStreetAddress() {
        return normalizedStreetAddress;
    }

    /**
     * Sets the value of the normalizedStreetAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNormalizedStreetAddress(String value) {
        this.normalizedStreetAddress = value;
    }

    /**
     * Gets the value of the normalizedMunicipality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNormalizedMunicipality() {
        return normalizedMunicipality;
    }

    /**
     * Sets the value of the normalizedMunicipality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNormalizedMunicipality(String value) {
        this.normalizedMunicipality = value;
    }

    /**
     * Gets the value of the normalizedRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNormalizedRegion() {
        return normalizedRegion;
    }

    /**
     * Sets the value of the normalizedRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNormalizedRegion(String value) {
        this.normalizedRegion = value;
    }

    /**
     * Gets the value of the normalizedPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNormalizedPostalCode() {
        return normalizedPostalCode;
    }

    /**
     * Sets the value of the normalizedPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNormalizedPostalCode(String value) {
        this.normalizedPostalCode = value;
    }

    /**
     * Gets the value of the normalizedCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNormalizedCountryCode() {
        return normalizedCountryCode;
    }

    /**
     * Sets the value of the normalizedCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNormalizedCountryCode(String value) {
        this.normalizedCountryCode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://sovren.com/hr-xml/2006-02-28>LatitudeType">
     *       &lt;attGroup ref="{http://sovren.com/hr-xml/2006-02-28}Inferred"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Latitude {

        @XmlValue
        protected BigDecimal value;
        @XmlAttribute(name = "inferred")
        protected Boolean inferred;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setValue(BigDecimal value) {
            this.value = value;
        }

        /**
         * Gets the value of the inferred property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isInferred() {
            return inferred;
        }

        /**
         * Sets the value of the inferred property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setInferred(Boolean value) {
            this.inferred = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://sovren.com/hr-xml/2006-02-28>LongitudeType">
     *       &lt;attGroup ref="{http://sovren.com/hr-xml/2006-02-28}Inferred"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Longitude {

        @XmlValue
        protected BigDecimal value;
        @XmlAttribute(name = "inferred")
        protected Boolean inferred;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setValue(BigDecimal value) {
            this.value = value;
        }

        /**
         * Gets the value of the inferred property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isInferred() {
            return inferred;
        }

        /**
         * Sets the value of the inferred property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setInferred(Boolean value) {
            this.inferred = value;
        }

    }

}
