//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//


package com.portal.job.resumeparsing.xmlparsing.userArea.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MaritalStatusEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MaritalStatusEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Married"/>
 *     &lt;enumeration value="Single"/>
 *     &lt;enumeration value="Divorced"/>
 *     &lt;enumeration value="Separated"/>
 *     &lt;enumeration value="CivilUnion"/>
 *     &lt;enumeration value="Cohabitating"/>
 *     &lt;enumeration value="Unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MaritalStatusEnum")
@XmlEnum
public enum MaritalStatusEnum {

    @XmlEnumValue("Married")
    MARRIED("Married"),
    @XmlEnumValue("Single")
    SINGLE("Single"),
    @XmlEnumValue("Divorced")
    DIVORCED("Divorced"),
    @XmlEnumValue("Separated")
    SEPARATED("Separated"),
    @XmlEnumValue("CivilUnion")
    CIVIL_UNION("CivilUnion"),
    @XmlEnumValue("Cohabitating")
    COHABITATING("Cohabitating"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    MaritalStatusEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MaritalStatusEnum fromValue(String v) {
        for (MaritalStatusEnum c: MaritalStatusEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
