//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//


package com.portal.job.resumeparsing.xmlparsing.userArea.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NationalIdentityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NationalIdentityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NationalIdentityNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NationalIdentityPhrase" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NationalIdentityType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NationalIdentityType", propOrder = {
    "nationalIdentityNumber",
    "nationalIdentityPhrase",
    "nationalIdentityType"
})
public class NationalIdentityType {

    @XmlElement(name = "NationalIdentityNumber")
    protected String nationalIdentityNumber;
    @XmlElement(name = "NationalIdentityPhrase")
    protected String nationalIdentityPhrase;
    @XmlElement(name = "NationalIdentityType")
    protected String nationalIdentityType;

    /**
     * Gets the value of the nationalIdentityNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationalIdentityNumber() {
        return nationalIdentityNumber;
    }

    /**
     * Sets the value of the nationalIdentityNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationalIdentityNumber(String value) {
        this.nationalIdentityNumber = value;
    }

    /**
     * Gets the value of the nationalIdentityPhrase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationalIdentityPhrase() {
        return nationalIdentityPhrase;
    }

    /**
     * Sets the value of the nationalIdentityPhrase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationalIdentityPhrase(String value) {
        this.nationalIdentityPhrase = value;
    }

    /**
     * Gets the value of the nationalIdentityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationalIdentityType() {
        return nationalIdentityType;
    }

    /**
     * Sets the value of the nationalIdentityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationalIdentityType(String value) {
        this.nationalIdentityType = value;
    }

}
