//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//


package com.portal.job.resumeparsing.xmlparsing.userArea.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sovren.hr_xml._2006_02_28 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ResumeUserAreaFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sovren.hr_xml._2006_02_28
     * 
     */
    public ResumeUserAreaFactory() {
    }

    /**
     * Create an instance of {@link ResumeUserArea }
     * 
     */
    public ResumeUserArea createResumeUserArea() {
        return new ResumeUserArea();
    }

    /**
     * Create an instance of {@link TrainingType }
     * 
     */
    public TrainingType createTrainingType() {
        return new TrainingType();
    }

    /**
     * Create an instance of {@link ResumeUserArea.ReservedData }
     * 
     */
    public ResumeUserArea.ReservedData createResumeUserAreaReservedData() {
        return new ResumeUserArea.ReservedData();
    }

    /**
     * Create an instance of {@link ResumeUserArea.CustomData }
     * 
     */
    public ResumeUserArea.CustomData createResumeUserAreaCustomData() {
        return new ResumeUserArea.CustomData();
    }

    /**
     * Create an instance of {@link ResumeUserArea.Sections }
     * 
     */
    public ResumeUserArea.Sections createResumeUserAreaSections() {
        return new ResumeUserArea.Sections();
    }

    /**
     * Create an instance of {@link ResumeUserArea.ExperienceSummary }
     * 
     */
    public ResumeUserArea.ExperienceSummary createResumeUserAreaExperienceSummary() {
        return new ResumeUserArea.ExperienceSummary();
    }

    /**
     * Create an instance of {@link ResumeUserArea.PersonalInformation }
     * 
     */
    public ResumeUserArea.PersonalInformation createResumeUserAreaPersonalInformation() {
        return new ResumeUserArea.PersonalInformation();
    }

    /**
     * Create an instance of {@link IndustryType }
     * 
     */
    public IndustryType createIndustryType() {
        return new IndustryType();
    }

    /**
     * Create an instance of {@link BulletsType }
     * 
     */
    public BulletsType createBulletsType() {
        return new BulletsType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link DegreeUserArea }
     * 
     */
    public DegreeUserArea createDegreeUserArea() {
        return new DegreeUserArea();
    }

    /**
     * Create an instance of {@link PositionHistoryUserArea }
     * 
     */
    public PositionHistoryUserArea createPositionHistoryUserArea() {
        return new PositionHistoryUserArea();
    }

    /**
     * Create an instance of {@link CultureType }
     * 
     */
    public CultureType createCultureType() {
        return new CultureType();
    }

    /**
     * Create an instance of {@link ResumeUserArea.TrainingHistory }
     * 
     */
    public ResumeUserArea.TrainingHistory createResumeUserAreaTrainingHistory() {
        return new ResumeUserArea.TrainingHistory();
    }

    /**
     * Create an instance of {@link ResumeUserArea.Hobbies }
     * 
     */
    public ResumeUserArea.Hobbies createResumeUserAreaHobbies() {
        return new ResumeUserArea.Hobbies();
    }

    /**
     * Create an instance of {@link ResumeUserArea.TimedOut }
     * 
     */
    public ResumeUserArea.TimedOut createResumeUserAreaTimedOut() {
        return new ResumeUserArea.TimedOut();
    }

    /**
     * Create an instance of {@link EmployerOrgUserArea }
     * 
     */
    public EmployerOrgUserArea createEmployerOrgUserArea() {
        return new EmployerOrgUserArea();
    }

    /**
     * Create an instance of {@link NationalityType }
     * 
     */
    public NationalityType createNationalityType() {
        return new NationalityType();
    }

    /**
     * Create an instance of {@link TrainingHistoryTypeType }
     * 
     */
    public TrainingHistoryTypeType createTrainingHistoryTypeType() {
        return new TrainingHistoryTypeType();
    }

    /**
     * Create an instance of {@link CurrentManagementLevelType }
     * 
     */
    public CurrentManagementLevelType createCurrentManagementLevelType() {
        return new CurrentManagementLevelType();
    }

    /**
     * Create an instance of {@link MaritalStatusType }
     * 
     */
    public MaritalStatusType createMaritalStatusType() {
        return new MaritalStatusType();
    }

    /**
     * Create an instance of {@link MessagingAddressType }
     * 
     */
    public MessagingAddressType createMessagingAddressType() {
        return new MessagingAddressType();
    }

    /**
     * Create an instance of {@link BestFitTaxonomyType }
     * 
     */
    public BestFitTaxonomyType createBestFitTaxonomyType() {
        return new BestFitTaxonomyType();
    }

    /**
     * Create an instance of {@link NationalIdentityType }
     * 
     */
    public NationalIdentityType createNationalIdentityType() {
        return new NationalIdentityType();
    }

    /**
     * Create an instance of {@link DateOfBirthType }
     * 
     */
    public DateOfBirthType createDateOfBirthType() {
        return new DateOfBirthType();
    }

    /**
     * Create an instance of {@link GenderType }
     * 
     */
    public GenderType createGenderType() {
        return new GenderType();
    }

    /**
     * Create an instance of {@link ExecutiveTypeType }
     * 
     */
    public ExecutiveTypeType createExecutiveTypeType() {
        return new ExecutiveTypeType();
    }

    /**
     * Create an instance of {@link MoneyType }
     * 
     */
    public MoneyType createMoneyType() {
        return new MoneyType();
    }

    /**
     * Create an instance of {@link TrainingType.Qualifications }
     * 
     */
    public TrainingType.Qualifications createTrainingTypeQualifications() {
        return new TrainingType.Qualifications();
    }

    /**
     * Create an instance of {@link ResumeUserArea.ReservedData.Phones }
     * 
     */
    public ResumeUserArea.ReservedData.Phones createResumeUserAreaReservedDataPhones() {
        return new ResumeUserArea.ReservedData.Phones();
    }

    /**
     * Create an instance of {@link ResumeUserArea.ReservedData.EmailAddresses }
     * 
     */
    public ResumeUserArea.ReservedData.EmailAddresses createResumeUserAreaReservedDataEmailAddresses() {
        return new ResumeUserArea.ReservedData.EmailAddresses();
    }

    /**
     * Create an instance of {@link ResumeUserArea.ReservedData.Urls }
     * 
     */
    public ResumeUserArea.ReservedData.Urls createResumeUserAreaReservedDataUrls() {
        return new ResumeUserArea.ReservedData.Urls();
    }

    /**
     * Create an instance of {@link ResumeUserArea.ReservedData.TwitterHandles }
     * 
     */
    public ResumeUserArea.ReservedData.TwitterHandles createResumeUserAreaReservedDataTwitterHandles() {
        return new ResumeUserArea.ReservedData.TwitterHandles();
    }

    /**
     * Create an instance of {@link ResumeUserArea.ReservedData.OtherData }
     * 
     */
    public ResumeUserArea.ReservedData.OtherData createResumeUserAreaReservedDataOtherData() {
        return new ResumeUserArea.ReservedData.OtherData();
    }

    /**
     * Create an instance of {@link ResumeUserArea.CustomData.CustomDataMatch }
     * 
     */
    public ResumeUserArea.CustomData.CustomDataMatch createResumeUserAreaCustomDataCustomDataMatch() {
        return new ResumeUserArea.CustomData.CustomDataMatch();
    }

    /**
     * Create an instance of {@link ResumeUserArea.Sections.Section }
     * 
     */
    public ResumeUserArea.Sections.Section createResumeUserAreaSectionsSection() {
        return new ResumeUserArea.Sections.Section();
    }

    /**
     * Create an instance of {@link ResumeUserArea.ExperienceSummary.BestFitTaxonomies }
     * 
     */
    public ResumeUserArea.ExperienceSummary.BestFitTaxonomies createResumeUserAreaExperienceSummaryBestFitTaxonomies() {
        return new ResumeUserArea.ExperienceSummary.BestFitTaxonomies();
    }

    /**
     * Create an instance of {@link ResumeUserArea.PersonalInformation.NationalIdentities }
     * 
     */
    public ResumeUserArea.PersonalInformation.NationalIdentities createResumeUserAreaPersonalInformationNationalIdentities() {
        return new ResumeUserArea.PersonalInformation.NationalIdentities();
    }

    /**
     * Create an instance of {@link IndustryType.Code }
     * 
     */
    public IndustryType.Code createIndustryTypeCode() {
        return new IndustryType.Code();
    }

    /**
     * Create an instance of {@link BulletsType.Bullet }
     * 
     */
    public BulletsType.Bullet createBulletsTypeBullet() {
        return new BulletsType.Bullet();
    }

    /**
     * Create an instance of {@link LocationType.Latitude }
     * 
     */
    public LocationType.Latitude createLocationTypeLatitude() {
        return new LocationType.Latitude();
    }

    /**
     * Create an instance of {@link LocationType.Longitude }
     * 
     */
    public LocationType.Longitude createLocationTypeLongitude() {
        return new LocationType.Longitude();
    }

}
