//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//


package com.portal.job.resumeparsing.xmlparsing.userArea.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Culture" type="{http://sovren.com/hr-xml/2006-02-28}CultureType" minOccurs="0"/>
 *         &lt;element name="Location" type="{http://sovren.com/hr-xml/2006-02-28}LocationType" minOccurs="0"/>
 *         &lt;element name="PersonalInformation" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DateOfBirth" type="{http://sovren.com/hr-xml/2006-02-28}DateOfBirthType" minOccurs="0"/>
 *                   &lt;element name="Birthplace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Nationality" type="{http://sovren.com/hr-xml/2006-02-28}NationalityType" minOccurs="0"/>
 *                   &lt;element name="NationalIdentities" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="NationalIdentity" type="{http://sovren.com/hr-xml/2006-02-28}NationalIdentityType" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Gender" type="{http://sovren.com/hr-xml/2006-02-28}GenderType" minOccurs="0"/>
 *                   &lt;element name="MaritalStatus" type="{http://sovren.com/hr-xml/2006-02-28}MaritalStatusType" minOccurs="0"/>
 *                   &lt;element name="DrivingLicense" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="CurrentLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="PreferredLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="WillingToRelocate" type="{http://sovren.com/hr-xml/2006-02-28}YesNoType" minOccurs="0"/>
 *                   &lt;element name="FamilyComposition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="FathersName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="MothersMaidenName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Availability" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="VisaStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="PassportNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="CurrentSalary" type="{http://sovren.com/hr-xml/2006-02-28}MoneyType" minOccurs="0"/>
 *                   &lt;element name="RequiredSalary" type="{http://sovren.com/hr-xml/2006-02-28}MoneyType" minOccurs="0"/>
 *                   &lt;element name="HukouCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="HukouArea" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="PoliticalAffiliation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="MessagingAddress" type="{http://sovren.com/hr-xml/2006-02-28}MessagingAddressType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="MotherTongue" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="[a-z][a-z]"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ExperienceSummary">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="MonthsOfWorkExperience" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="YearsOfWorkExperience" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="MonthsOfManagementExperience" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="YearsOfManagementExperience" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="CurrentManagementLevel" type="{http://sovren.com/hr-xml/2006-02-28}CurrentManagementLevelType" minOccurs="0"/>
 *                   &lt;element name="HighestManagementScore" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="ExecutiveType" type="{http://sovren.com/hr-xml/2006-02-28}ExecutiveTypeType" minOccurs="0"/>
 *                   &lt;element name="ManagementStory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="BestFitTaxonomies" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="BestFitTaxonomy" type="{http://sovren.com/hr-xml/2006-02-28}BestFitTaxonomyType" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TrainingHistory" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Training" type="{http://sovren.com/hr-xml/2006-02-28}TrainingType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Hobbies" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Sections" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Section" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="starts" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="ends" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="sectionType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CustomData" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CustomDataMatch" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ReservedData" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Phones" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="EmailAddresses" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Urls" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="TwitterHandles" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="TwitterHandle" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="OtherData" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="OtherDatum" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CoverLetterText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ParsedTextLength" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="SearchHints" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ParseTime" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="TimedOut" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
 *                 &lt;attribute name="type" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="hard"/>
 *                       &lt;enumeration value="soft"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="LicenseSerialNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ParserConfigurationString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ParserVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "culture",
    "location",
    "personalInformation",
    "experienceSummary",
    "trainingHistory",
    "hobbies",
    "sections",
    "customData",
    "reservedData",
    "coverLetterText",
    "parsedTextLength",
    "searchHints",
    "parseTime",
    "timedOut",
    "licenseSerialNumber",
    "parserConfigurationString",
    "parserVersion"
})
@XmlRootElement(name = "ResumeUserArea")
public class ResumeUserArea {

    @XmlElement(name = "Culture")
    protected CultureType culture;
    @XmlElement(name = "Location")
    protected LocationType location;
    @XmlElement(name = "PersonalInformation")
    protected ResumeUserArea.PersonalInformation personalInformation;
    @XmlElement(name = "ExperienceSummary", required = true)
    protected ResumeUserArea.ExperienceSummary experienceSummary;
    @XmlElement(name = "TrainingHistory")
    protected ResumeUserArea.TrainingHistory trainingHistory;
    @XmlElement(name = "Hobbies")
    protected ResumeUserArea.Hobbies hobbies;
    @XmlElement(name = "Sections")
    protected ResumeUserArea.Sections sections;
    @XmlElement(name = "CustomData")
    protected ResumeUserArea.CustomData customData;
    @XmlElement(name = "ReservedData")
    protected ResumeUserArea.ReservedData reservedData;
    @XmlElement(name = "CoverLetterText")
    protected String coverLetterText;
    @XmlElement(name = "ParsedTextLength")
    protected int parsedTextLength;
    @XmlElement(name = "SearchHints")
    protected String searchHints;
    @XmlElement(name = "ParseTime")
    protected Integer parseTime;
    @XmlElement(name = "TimedOut")
    protected ResumeUserArea.TimedOut timedOut;
    @XmlElement(name = "LicenseSerialNumber")
    protected String licenseSerialNumber;
    @XmlElement(name = "ParserConfigurationString")
    protected String parserConfigurationString;
    @XmlElement(name = "ParserVersion", required = true)
    protected String parserVersion;

    /**
     * Gets the value of the culture property.
     * 
     * @return
     *     possible object is
     *     {@link CultureType }
     *     
     */
    public CultureType getCulture() {
        return culture;
    }

    /**
     * Sets the value of the culture property.
     * 
     * @param value
     *     allowed object is
     *     {@link CultureType }
     *     
     */
    public void setCulture(CultureType value) {
        this.culture = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link LocationType }
     *     
     */
    public LocationType getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationType }
     *     
     */
    public void setLocation(LocationType value) {
        this.location = value;
    }

    /**
     * Gets the value of the personalInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ResumeUserArea.PersonalInformation }
     *     
     */
    public ResumeUserArea.PersonalInformation getPersonalInformation() {
        return personalInformation;
    }

    /**
     * Sets the value of the personalInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResumeUserArea.PersonalInformation }
     *     
     */
    public void setPersonalInformation(ResumeUserArea.PersonalInformation value) {
        this.personalInformation = value;
    }

    /**
     * Gets the value of the experienceSummary property.
     * 
     * @return
     *     possible object is
     *     {@link ResumeUserArea.ExperienceSummary }
     *     
     */
    public ResumeUserArea.ExperienceSummary getExperienceSummary() {
        return experienceSummary;
    }

    /**
     * Sets the value of the experienceSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResumeUserArea.ExperienceSummary }
     *     
     */
    public void setExperienceSummary(ResumeUserArea.ExperienceSummary value) {
        this.experienceSummary = value;
    }

    /**
     * Gets the value of the trainingHistory property.
     * 
     * @return
     *     possible object is
     *     {@link ResumeUserArea.TrainingHistory }
     *     
     */
    public ResumeUserArea.TrainingHistory getTrainingHistory() {
        return trainingHistory;
    }

    /**
     * Sets the value of the trainingHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResumeUserArea.TrainingHistory }
     *     
     */
    public void setTrainingHistory(ResumeUserArea.TrainingHistory value) {
        this.trainingHistory = value;
    }

    /**
     * Gets the value of the hobbies property.
     * 
     * @return
     *     possible object is
     *     {@link ResumeUserArea.Hobbies }
     *     
     */
    public ResumeUserArea.Hobbies getHobbies() {
        return hobbies;
    }

    /**
     * Sets the value of the hobbies property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResumeUserArea.Hobbies }
     *     
     */
    public void setHobbies(ResumeUserArea.Hobbies value) {
        this.hobbies = value;
    }

    /**
     * Gets the value of the sections property.
     * 
     * @return
     *     possible object is
     *     {@link ResumeUserArea.Sections }
     *     
     */
    public ResumeUserArea.Sections getSections() {
        return sections;
    }

    /**
     * Sets the value of the sections property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResumeUserArea.Sections }
     *     
     */
    public void setSections(ResumeUserArea.Sections value) {
        this.sections = value;
    }

    /**
     * Gets the value of the customData property.
     * 
     * @return
     *     possible object is
     *     {@link ResumeUserArea.CustomData }
     *     
     */
    public ResumeUserArea.CustomData getCustomData() {
        return customData;
    }

    /**
     * Sets the value of the customData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResumeUserArea.CustomData }
     *     
     */
    public void setCustomData(ResumeUserArea.CustomData value) {
        this.customData = value;
    }

    /**
     * Gets the value of the reservedData property.
     * 
     * @return
     *     possible object is
     *     {@link ResumeUserArea.ReservedData }
     *     
     */
    public ResumeUserArea.ReservedData getReservedData() {
        return reservedData;
    }

    /**
     * Sets the value of the reservedData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResumeUserArea.ReservedData }
     *     
     */
    public void setReservedData(ResumeUserArea.ReservedData value) {
        this.reservedData = value;
    }

    /**
     * Gets the value of the coverLetterText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverLetterText() {
        return coverLetterText;
    }

    /**
     * Sets the value of the coverLetterText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverLetterText(String value) {
        this.coverLetterText = value;
    }

    /**
     * Gets the value of the parsedTextLength property.
     * 
     */
    public int getParsedTextLength() {
        return parsedTextLength;
    }

    /**
     * Sets the value of the parsedTextLength property.
     * 
     */
    public void setParsedTextLength(int value) {
        this.parsedTextLength = value;
    }

    /**
     * Gets the value of the searchHints property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchHints() {
        return searchHints;
    }

    /**
     * Sets the value of the searchHints property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchHints(String value) {
        this.searchHints = value;
    }

    /**
     * Gets the value of the parseTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getParseTime() {
        return parseTime;
    }

    /**
     * Sets the value of the parseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setParseTime(Integer value) {
        this.parseTime = value;
    }

    /**
     * Gets the value of the timedOut property.
     * 
     * @return
     *     possible object is
     *     {@link ResumeUserArea.TimedOut }
     *     
     */
    public ResumeUserArea.TimedOut getTimedOut() {
        return timedOut;
    }

    /**
     * Sets the value of the timedOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResumeUserArea.TimedOut }
     *     
     */
    public void setTimedOut(ResumeUserArea.TimedOut value) {
        this.timedOut = value;
    }

    /**
     * Gets the value of the licenseSerialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseSerialNumber() {
        return licenseSerialNumber;
    }

    /**
     * Sets the value of the licenseSerialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseSerialNumber(String value) {
        this.licenseSerialNumber = value;
    }

    /**
     * Gets the value of the parserConfigurationString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParserConfigurationString() {
        return parserConfigurationString;
    }

    /**
     * Sets the value of the parserConfigurationString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParserConfigurationString(String value) {
        this.parserConfigurationString = value;
    }

    /**
     * Gets the value of the parserVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParserVersion() {
        return parserVersion;
    }

    /**
     * Sets the value of the parserVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParserVersion(String value) {
        this.parserVersion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CustomDataMatch" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "customDataMatch"
    })
    public static class CustomData {

        @XmlElement(name = "CustomDataMatch")
        protected List<ResumeUserArea.CustomData.CustomDataMatch> customDataMatch;

        /**
         * Gets the value of the customDataMatch property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the customDataMatch property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCustomDataMatch().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResumeUserArea.CustomData.CustomDataMatch }
         * 
         * 
         */
        public List<ResumeUserArea.CustomData.CustomDataMatch> getCustomDataMatch() {
            if (customDataMatch == null) {
                customDataMatch = new ArrayList<ResumeUserArea.CustomData.CustomDataMatch>();
            }
            return this.customDataMatch;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class CustomDataMatch {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "type", required = true)
            protected String type;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="MonthsOfWorkExperience" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="YearsOfWorkExperience" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="MonthsOfManagementExperience" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="YearsOfManagementExperience" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="CurrentManagementLevel" type="{http://sovren.com/hr-xml/2006-02-28}CurrentManagementLevelType" minOccurs="0"/>
     *         &lt;element name="HighestManagementScore" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="ExecutiveType" type="{http://sovren.com/hr-xml/2006-02-28}ExecutiveTypeType" minOccurs="0"/>
     *         &lt;element name="ManagementStory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="BestFitTaxonomies" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="BestFitTaxonomy" type="{http://sovren.com/hr-xml/2006-02-28}BestFitTaxonomyType" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "description",
        "monthsOfWorkExperience",
        "yearsOfWorkExperience",
        "monthsOfManagementExperience",
        "yearsOfManagementExperience",
        "currentManagementLevel",
        "highestManagementScore",
        "executiveType",
        "managementStory",
        "bestFitTaxonomies"
    })
    public static class ExperienceSummary {

        @XmlElement(name = "Description")
        protected String description;
        @XmlElement(name = "MonthsOfWorkExperience")
        protected Integer monthsOfWorkExperience;
        @XmlElement(name = "YearsOfWorkExperience")
        protected Integer yearsOfWorkExperience;
        @XmlElement(name = "MonthsOfManagementExperience")
        protected Integer monthsOfManagementExperience;
        @XmlElement(name = "YearsOfManagementExperience")
        protected Integer yearsOfManagementExperience;
        @XmlElement(name = "CurrentManagementLevel")
        protected CurrentManagementLevelType currentManagementLevel;
        @XmlElement(name = "HighestManagementScore")
        protected Integer highestManagementScore;
        @XmlElement(name = "ExecutiveType")
        protected ExecutiveTypeType executiveType;
        @XmlElement(name = "ManagementStory")
        protected String managementStory;
        @XmlElement(name = "BestFitTaxonomies")
        protected ResumeUserArea.ExperienceSummary.BestFitTaxonomies bestFitTaxonomies;

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the monthsOfWorkExperience property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getMonthsOfWorkExperience() {
            return monthsOfWorkExperience;
        }

        /**
         * Sets the value of the monthsOfWorkExperience property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setMonthsOfWorkExperience(Integer value) {
            this.monthsOfWorkExperience = value;
        }

        /**
         * Gets the value of the yearsOfWorkExperience property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getYearsOfWorkExperience() {
            return yearsOfWorkExperience;
        }

        /**
         * Sets the value of the yearsOfWorkExperience property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setYearsOfWorkExperience(Integer value) {
            this.yearsOfWorkExperience = value;
        }

        /**
         * Gets the value of the monthsOfManagementExperience property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getMonthsOfManagementExperience() {
            return monthsOfManagementExperience;
        }

        /**
         * Sets the value of the monthsOfManagementExperience property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setMonthsOfManagementExperience(Integer value) {
            this.monthsOfManagementExperience = value;
        }

        /**
         * Gets the value of the yearsOfManagementExperience property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getYearsOfManagementExperience() {
            return yearsOfManagementExperience;
        }

        /**
         * Sets the value of the yearsOfManagementExperience property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setYearsOfManagementExperience(Integer value) {
            this.yearsOfManagementExperience = value;
        }

        /**
         * Gets the value of the currentManagementLevel property.
         * 
         * @return
         *     possible object is
         *     {@link CurrentManagementLevelType }
         *     
         */
        public CurrentManagementLevelType getCurrentManagementLevel() {
            return currentManagementLevel;
        }

        /**
         * Sets the value of the currentManagementLevel property.
         * 
         * @param value
         *     allowed object is
         *     {@link CurrentManagementLevelType }
         *     
         */
        public void setCurrentManagementLevel(CurrentManagementLevelType value) {
            this.currentManagementLevel = value;
        }

        /**
         * Gets the value of the highestManagementScore property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getHighestManagementScore() {
            return highestManagementScore;
        }

        /**
         * Sets the value of the highestManagementScore property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setHighestManagementScore(Integer value) {
            this.highestManagementScore = value;
        }

        /**
         * Gets the value of the executiveType property.
         * 
         * @return
         *     possible object is
         *     {@link ExecutiveTypeType }
         *     
         */
        public ExecutiveTypeType getExecutiveType() {
            return executiveType;
        }

        /**
         * Sets the value of the executiveType property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExecutiveTypeType }
         *     
         */
        public void setExecutiveType(ExecutiveTypeType value) {
            this.executiveType = value;
        }

        /**
         * Gets the value of the managementStory property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getManagementStory() {
            return managementStory;
        }

        /**
         * Sets the value of the managementStory property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setManagementStory(String value) {
            this.managementStory = value;
        }

        /**
         * Gets the value of the bestFitTaxonomies property.
         * 
         * @return
         *     possible object is
         *     {@link ResumeUserArea.ExperienceSummary.BestFitTaxonomies }
         *     
         */
        public ResumeUserArea.ExperienceSummary.BestFitTaxonomies getBestFitTaxonomies() {
            return bestFitTaxonomies;
        }

        /**
         * Sets the value of the bestFitTaxonomies property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResumeUserArea.ExperienceSummary.BestFitTaxonomies }
         *     
         */
        public void setBestFitTaxonomies(ResumeUserArea.ExperienceSummary.BestFitTaxonomies value) {
            this.bestFitTaxonomies = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="BestFitTaxonomy" type="{http://sovren.com/hr-xml/2006-02-28}BestFitTaxonomyType" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "bestFitTaxonomy"
        })
        public static class BestFitTaxonomies {

            @XmlElement(name = "BestFitTaxonomy")
            protected List<BestFitTaxonomyType> bestFitTaxonomy;

            /**
             * Gets the value of the bestFitTaxonomy property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the bestFitTaxonomy property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getBestFitTaxonomy().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BestFitTaxonomyType }
             * 
             * 
             */
            public List<BestFitTaxonomyType> getBestFitTaxonomy() {
                if (bestFitTaxonomy == null) {
                    bestFitTaxonomy = new ArrayList<BestFitTaxonomyType>();
                }
                return this.bestFitTaxonomy;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "text"
    })
    public static class Hobbies {

        @XmlElement(name = "Text", required = true)
        protected String text;

        /**
         * Gets the value of the text property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getText() {
            return text;
        }

        /**
         * Sets the value of the text property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setText(String value) {
            this.text = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DateOfBirth" type="{http://sovren.com/hr-xml/2006-02-28}DateOfBirthType" minOccurs="0"/>
     *         &lt;element name="Birthplace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Nationality" type="{http://sovren.com/hr-xml/2006-02-28}NationalityType" minOccurs="0"/>
     *         &lt;element name="NationalIdentities" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="NationalIdentity" type="{http://sovren.com/hr-xml/2006-02-28}NationalIdentityType" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Gender" type="{http://sovren.com/hr-xml/2006-02-28}GenderType" minOccurs="0"/>
     *         &lt;element name="MaritalStatus" type="{http://sovren.com/hr-xml/2006-02-28}MaritalStatusType" minOccurs="0"/>
     *         &lt;element name="DrivingLicense" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CurrentLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="PreferredLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="WillingToRelocate" type="{http://sovren.com/hr-xml/2006-02-28}YesNoType" minOccurs="0"/>
     *         &lt;element name="FamilyComposition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="FathersName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="MothersMaidenName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Availability" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="VisaStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="PassportNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CurrentSalary" type="{http://sovren.com/hr-xml/2006-02-28}MoneyType" minOccurs="0"/>
     *         &lt;element name="RequiredSalary" type="{http://sovren.com/hr-xml/2006-02-28}MoneyType" minOccurs="0"/>
     *         &lt;element name="HukouCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="HukouArea" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="PoliticalAffiliation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="MessagingAddress" type="{http://sovren.com/hr-xml/2006-02-28}MessagingAddressType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="MotherTongue" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="[a-z][a-z]"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dateOfBirth",
        "birthplace",
        "nationality",
        "nationalIdentities",
        "gender",
        "maritalStatus",
        "drivingLicense",
        "currentLocation",
        "preferredLocation",
        "willingToRelocate",
        "familyComposition",
        "fathersName",
        "mothersMaidenName",
        "availability",
        "visaStatus",
        "passportNumber",
        "currentSalary",
        "requiredSalary",
        "hukouCity",
        "hukouArea",
        "politicalAffiliation",
        "messagingAddress",
        "motherTongue"
    })
    public static class PersonalInformation {

        @XmlElement(name = "DateOfBirth")
        protected DateOfBirthType dateOfBirth;
        @XmlElement(name = "Birthplace")
        protected String birthplace;
        @XmlElement(name = "Nationality")
        protected NationalityType nationality;
        @XmlElement(name = "NationalIdentities")
        protected ResumeUserArea.PersonalInformation.NationalIdentities nationalIdentities;
        @XmlElement(name = "Gender")
        protected GenderType gender;
        @XmlElement(name = "MaritalStatus")
        protected MaritalStatusType maritalStatus;
        @XmlElement(name = "DrivingLicense")
        protected String drivingLicense;
        @XmlElement(name = "CurrentLocation")
        protected String currentLocation;
        @XmlElement(name = "PreferredLocation")
        protected String preferredLocation;
        @XmlElement(name = "WillingToRelocate")
        @XmlSchemaType(name = "string")
        protected YesNoType willingToRelocate;
        @XmlElement(name = "FamilyComposition")
        protected String familyComposition;
        @XmlElement(name = "FathersName")
        protected String fathersName;
        @XmlElement(name = "MothersMaidenName")
        protected String mothersMaidenName;
        @XmlElement(name = "Availability")
        protected String availability;
        @XmlElement(name = "VisaStatus")
        protected String visaStatus;
        @XmlElement(name = "PassportNumber")
        protected String passportNumber;
        @XmlElement(name = "CurrentSalary")
        protected MoneyType currentSalary;
        @XmlElement(name = "RequiredSalary")
        protected MoneyType requiredSalary;
        @XmlElement(name = "HukouCity")
        protected String hukouCity;
        @XmlElement(name = "HukouArea")
        protected String hukouArea;
        @XmlElement(name = "PoliticalAffiliation")
        protected String politicalAffiliation;
        @XmlElement(name = "MessagingAddress")
        protected List<MessagingAddressType> messagingAddress;
        @XmlElement(name = "MotherTongue")
        protected String motherTongue;

        /**
         * Gets the value of the dateOfBirth property.
         * 
         * @return
         *     possible object is
         *     {@link DateOfBirthType }
         *     
         */
        public DateOfBirthType getDateOfBirth() {
            return dateOfBirth;
        }

        /**
         * Sets the value of the dateOfBirth property.
         * 
         * @param value
         *     allowed object is
         *     {@link DateOfBirthType }
         *     
         */
        public void setDateOfBirth(DateOfBirthType value) {
            this.dateOfBirth = value;
        }

        /**
         * Gets the value of the birthplace property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBirthplace() {
            return birthplace;
        }

        /**
         * Sets the value of the birthplace property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBirthplace(String value) {
            this.birthplace = value;
        }

        /**
         * Gets the value of the nationality property.
         * 
         * @return
         *     possible object is
         *     {@link NationalityType }
         *     
         */
        public NationalityType getNationality() {
            return nationality;
        }

        /**
         * Sets the value of the nationality property.
         * 
         * @param value
         *     allowed object is
         *     {@link NationalityType }
         *     
         */
        public void setNationality(NationalityType value) {
            this.nationality = value;
        }

        /**
         * Gets the value of the nationalIdentities property.
         * 
         * @return
         *     possible object is
         *     {@link ResumeUserArea.PersonalInformation.NationalIdentities }
         *     
         */
        public ResumeUserArea.PersonalInformation.NationalIdentities getNationalIdentities() {
            return nationalIdentities;
        }

        /**
         * Sets the value of the nationalIdentities property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResumeUserArea.PersonalInformation.NationalIdentities }
         *     
         */
        public void setNationalIdentities(ResumeUserArea.PersonalInformation.NationalIdentities value) {
            this.nationalIdentities = value;
        }

        /**
         * Gets the value of the gender property.
         * 
         * @return
         *     possible object is
         *     {@link GenderType }
         *     
         */
        public GenderType getGender() {
            return gender;
        }

        /**
         * Sets the value of the gender property.
         * 
         * @param value
         *     allowed object is
         *     {@link GenderType }
         *     
         */
        public void setGender(GenderType value) {
            this.gender = value;
        }

        /**
         * Gets the value of the maritalStatus property.
         * 
         * @return
         *     possible object is
         *     {@link MaritalStatusType }
         *     
         */
        public MaritalStatusType getMaritalStatus() {
            return maritalStatus;
        }

        /**
         * Sets the value of the maritalStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link MaritalStatusType }
         *     
         */
        public void setMaritalStatus(MaritalStatusType value) {
            this.maritalStatus = value;
        }

        /**
         * Gets the value of the drivingLicense property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDrivingLicense() {
            return drivingLicense;
        }

        /**
         * Sets the value of the drivingLicense property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDrivingLicense(String value) {
            this.drivingLicense = value;
        }

        /**
         * Gets the value of the currentLocation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrentLocation() {
            return currentLocation;
        }

        /**
         * Sets the value of the currentLocation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrentLocation(String value) {
            this.currentLocation = value;
        }

        /**
         * Gets the value of the preferredLocation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPreferredLocation() {
            return preferredLocation;
        }

        /**
         * Sets the value of the preferredLocation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPreferredLocation(String value) {
            this.preferredLocation = value;
        }

        /**
         * Gets the value of the willingToRelocate property.
         * 
         * @return
         *     possible object is
         *     {@link YesNoType }
         *     
         */
        public YesNoType getWillingToRelocate() {
            return willingToRelocate;
        }

        /**
         * Sets the value of the willingToRelocate property.
         * 
         * @param value
         *     allowed object is
         *     {@link YesNoType }
         *     
         */
        public void setWillingToRelocate(YesNoType value) {
            this.willingToRelocate = value;
        }

        /**
         * Gets the value of the familyComposition property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFamilyComposition() {
            return familyComposition;
        }

        /**
         * Sets the value of the familyComposition property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFamilyComposition(String value) {
            this.familyComposition = value;
        }

        /**
         * Gets the value of the fathersName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFathersName() {
            return fathersName;
        }

        /**
         * Sets the value of the fathersName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFathersName(String value) {
            this.fathersName = value;
        }

        /**
         * Gets the value of the mothersMaidenName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMothersMaidenName() {
            return mothersMaidenName;
        }

        /**
         * Sets the value of the mothersMaidenName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMothersMaidenName(String value) {
            this.mothersMaidenName = value;
        }

        /**
         * Gets the value of the availability property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAvailability() {
            return availability;
        }

        /**
         * Sets the value of the availability property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAvailability(String value) {
            this.availability = value;
        }

        /**
         * Gets the value of the visaStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVisaStatus() {
            return visaStatus;
        }

        /**
         * Sets the value of the visaStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVisaStatus(String value) {
            this.visaStatus = value;
        }

        /**
         * Gets the value of the passportNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPassportNumber() {
            return passportNumber;
        }

        /**
         * Sets the value of the passportNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPassportNumber(String value) {
            this.passportNumber = value;
        }

        /**
         * Gets the value of the currentSalary property.
         * 
         * @return
         *     possible object is
         *     {@link MoneyType }
         *     
         */
        public MoneyType getCurrentSalary() {
            return currentSalary;
        }

        /**
         * Sets the value of the currentSalary property.
         * 
         * @param value
         *     allowed object is
         *     {@link MoneyType }
         *     
         */
        public void setCurrentSalary(MoneyType value) {
            this.currentSalary = value;
        }

        /**
         * Gets the value of the requiredSalary property.
         * 
         * @return
         *     possible object is
         *     {@link MoneyType }
         *     
         */
        public MoneyType getRequiredSalary() {
            return requiredSalary;
        }

        /**
         * Sets the value of the requiredSalary property.
         * 
         * @param value
         *     allowed object is
         *     {@link MoneyType }
         *     
         */
        public void setRequiredSalary(MoneyType value) {
            this.requiredSalary = value;
        }

        /**
         * Gets the value of the hukouCity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHukouCity() {
            return hukouCity;
        }

        /**
         * Sets the value of the hukouCity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHukouCity(String value) {
            this.hukouCity = value;
        }

        /**
         * Gets the value of the hukouArea property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHukouArea() {
            return hukouArea;
        }

        /**
         * Sets the value of the hukouArea property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHukouArea(String value) {
            this.hukouArea = value;
        }

        /**
         * Gets the value of the politicalAffiliation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPoliticalAffiliation() {
            return politicalAffiliation;
        }

        /**
         * Sets the value of the politicalAffiliation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPoliticalAffiliation(String value) {
            this.politicalAffiliation = value;
        }

        /**
         * Gets the value of the messagingAddress property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the messagingAddress property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMessagingAddress().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MessagingAddressType }
         * 
         * 
         */
        public List<MessagingAddressType> getMessagingAddress() {
            if (messagingAddress == null) {
                messagingAddress = new ArrayList<MessagingAddressType>();
            }
            return this.messagingAddress;
        }

        /**
         * Gets the value of the motherTongue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMotherTongue() {
            return motherTongue;
        }

        /**
         * Sets the value of the motherTongue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMotherTongue(String value) {
            this.motherTongue = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="NationalIdentity" type="{http://sovren.com/hr-xml/2006-02-28}NationalIdentityType" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nationalIdentity"
        })
        public static class NationalIdentities {

            @XmlElement(name = "NationalIdentity")
            protected List<NationalIdentityType> nationalIdentity;

            /**
             * Gets the value of the nationalIdentity property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the nationalIdentity property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getNationalIdentity().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link NationalIdentityType }
             * 
             * 
             */
            public List<NationalIdentityType> getNationalIdentity() {
                if (nationalIdentity == null) {
                    nationalIdentity = new ArrayList<NationalIdentityType>();
                }
                return this.nationalIdentity;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Phones" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="EmailAddresses" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Urls" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="TwitterHandles" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TwitterHandle" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="OtherData" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="OtherDatum" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "phones",
        "emailAddresses",
        "urls",
        "twitterHandles",
        "otherData"
    })
    public static class ReservedData {

        @XmlElement(name = "Phones")
        protected ResumeUserArea.ReservedData.Phones phones;
        @XmlElement(name = "EmailAddresses")
        protected ResumeUserArea.ReservedData.EmailAddresses emailAddresses;
        @XmlElement(name = "Urls")
        protected ResumeUserArea.ReservedData.Urls urls;
        @XmlElement(name = "TwitterHandles")
        protected ResumeUserArea.ReservedData.TwitterHandles twitterHandles;
        @XmlElement(name = "OtherData")
        protected ResumeUserArea.ReservedData.OtherData otherData;

        /**
         * Gets the value of the phones property.
         * 
         * @return
         *     possible object is
         *     {@link ResumeUserArea.ReservedData.Phones }
         *     
         */
        public ResumeUserArea.ReservedData.Phones getPhones() {
            return phones;
        }

        /**
         * Sets the value of the phones property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResumeUserArea.ReservedData.Phones }
         *     
         */
        public void setPhones(ResumeUserArea.ReservedData.Phones value) {
            this.phones = value;
        }

        /**
         * Gets the value of the emailAddresses property.
         * 
         * @return
         *     possible object is
         *     {@link ResumeUserArea.ReservedData.EmailAddresses }
         *     
         */
        public ResumeUserArea.ReservedData.EmailAddresses getEmailAddresses() {
            return emailAddresses;
        }

        /**
         * Sets the value of the emailAddresses property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResumeUserArea.ReservedData.EmailAddresses }
         *     
         */
        public void setEmailAddresses(ResumeUserArea.ReservedData.EmailAddresses value) {
            this.emailAddresses = value;
        }

        /**
         * Gets the value of the urls property.
         * 
         * @return
         *     possible object is
         *     {@link ResumeUserArea.ReservedData.Urls }
         *     
         */
        public ResumeUserArea.ReservedData.Urls getUrls() {
            return urls;
        }

        /**
         * Sets the value of the urls property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResumeUserArea.ReservedData.Urls }
         *     
         */
        public void setUrls(ResumeUserArea.ReservedData.Urls value) {
            this.urls = value;
        }

        /**
         * Gets the value of the twitterHandles property.
         * 
         * @return
         *     possible object is
         *     {@link ResumeUserArea.ReservedData.TwitterHandles }
         *     
         */
        public ResumeUserArea.ReservedData.TwitterHandles getTwitterHandles() {
            return twitterHandles;
        }

        /**
         * Sets the value of the twitterHandles property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResumeUserArea.ReservedData.TwitterHandles }
         *     
         */
        public void setTwitterHandles(ResumeUserArea.ReservedData.TwitterHandles value) {
            this.twitterHandles = value;
        }

        /**
         * Gets the value of the otherData property.
         * 
         * @return
         *     possible object is
         *     {@link ResumeUserArea.ReservedData.OtherData }
         *     
         */
        public ResumeUserArea.ReservedData.OtherData getOtherData() {
            return otherData;
        }

        /**
         * Sets the value of the otherData property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResumeUserArea.ReservedData.OtherData }
         *     
         */
        public void setOtherData(ResumeUserArea.ReservedData.OtherData value) {
            this.otherData = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "emailAddress"
        })
        public static class EmailAddresses {

            @XmlElement(name = "EmailAddress")
            protected List<String> emailAddress;

            /**
             * Gets the value of the emailAddress property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the emailAddress property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getEmailAddress().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getEmailAddress() {
                if (emailAddress == null) {
                    emailAddress = new ArrayList<String>();
                }
                return this.emailAddress;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="OtherDatum" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "otherDatum"
        })
        public static class OtherData {

            @XmlElement(name = "OtherDatum")
            protected List<String> otherDatum;

            /**
             * Gets the value of the otherDatum property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the otherDatum property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getOtherDatum().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getOtherDatum() {
                if (otherDatum == null) {
                    otherDatum = new ArrayList<String>();
                }
                return this.otherDatum;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "phone"
        })
        public static class Phones {

            @XmlElement(name = "Phone")
            protected List<String> phone;

            /**
             * Gets the value of the phone property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the phone property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPhone().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getPhone() {
                if (phone == null) {
                    phone = new ArrayList<String>();
                }
                return this.phone;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TwitterHandle" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "twitterHandle"
        })
        public static class TwitterHandles {

            @XmlElement(name = "TwitterHandle")
            protected List<String> twitterHandle;

            /**
             * Gets the value of the twitterHandle property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the twitterHandle property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTwitterHandle().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getTwitterHandle() {
                if (twitterHandle == null) {
                    twitterHandle = new ArrayList<String>();
                }
                return this.twitterHandle;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "url"
        })
        public static class Urls {

            @XmlElement(name = "Url")
            protected List<String> url;

            /**
             * Gets the value of the url property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the url property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getUrl().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getUrl() {
                if (url == null) {
                    url = new ArrayList<String>();
                }
                return this.url;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Section" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="starts" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="ends" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="sectionType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "section"
    })
    public static class Sections {

        @XmlElement(name = "Section")
        protected List<ResumeUserArea.Sections.Section> section;

        /**
         * Gets the value of the section property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the section property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSection().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResumeUserArea.Sections.Section }
         * 
         * 
         */
        public List<ResumeUserArea.Sections.Section> getSection() {
            if (section == null) {
                section = new ArrayList<ResumeUserArea.Sections.Section>();
            }
            return this.section;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="starts" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="ends" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="sectionType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Section {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "starts", required = true)
            protected int starts;
            @XmlAttribute(name = "ends", required = true)
            protected int ends;
            @XmlAttribute(name = "sectionType", required = true)
            protected String sectionType;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the starts property.
             * 
             */
            public int getStarts() {
                return starts;
            }

            /**
             * Sets the value of the starts property.
             * 
             */
            public void setStarts(int value) {
                this.starts = value;
            }

            /**
             * Gets the value of the ends property.
             * 
             */
            public int getEnds() {
                return ends;
            }

            /**
             * Sets the value of the ends property.
             * 
             */
            public void setEnds(int value) {
                this.ends = value;
            }

            /**
             * Gets the value of the sectionType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSectionType() {
                return sectionType;
            }

            /**
             * Sets the value of the sectionType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSectionType(String value) {
                this.sectionType = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
     *       &lt;attribute name="type" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="hard"/>
     *             &lt;enumeration value="soft"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class TimedOut {

        @XmlValue
        protected int value;
        @XmlAttribute(name = "type", required = true)
        protected String type;

        /**
         * Gets the value of the value property.
         * 
         */
        public int getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(int value) {
            this.value = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Training" type="{http://sovren.com/hr-xml/2006-02-28}TrainingType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "text",
        "training"
    })
    public static class TrainingHistory {

        @XmlElement(name = "Text")
        protected String text;
        @XmlElement(name = "Training")
        protected List<TrainingType> training;

        /**
         * Gets the value of the text property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getText() {
            return text;
        }

        /**
         * Sets the value of the text property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setText(String value) {
            this.text = value;
        }

        /**
         * Gets the value of the training property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the training property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTraining().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TrainingType }
         * 
         * 
         */
        public List<TrainingType> getTraining() {
            if (training == null) {
                training = new ArrayList<TrainingType>();
            }
            return this.training;
        }

    }

}
