//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//


package com.portal.job.resumeparsing.xmlparsing.userArea.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for TrainingHistoryTypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrainingHistoryTypeType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://sovren.com/hr-xml/2006-02-28>TrainingHistoryTypeEnum">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrainingHistoryTypeType", propOrder = {
    "value"
})
public class TrainingHistoryTypeType {

    @XmlValue
    protected TrainingHistoryTypeEnum value;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link TrainingHistoryTypeEnum }
     *     
     */
    public TrainingHistoryTypeEnum getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrainingHistoryTypeEnum }
     *     
     */
    public void setValue(TrainingHistoryTypeEnum value) {
        this.value = value;
    }

}
