//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//


package com.portal.job.resumeparsing.xmlparsing.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AcademicCreditCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AcademicCreditCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="G"/>
 *     &lt;enumeration value="N"/>
 *     &lt;enumeration value="Q"/>
 *     &lt;enumeration value="S"/>
 *     &lt;enumeration value="U"/>
 *     &lt;enumeration value="V"/>
 *     &lt;enumeration value="X"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AcademicCreditCodeType")
@XmlEnum
public enum AcademicCreditCodeType {


    /**
     * Adult Credits
     * 
     */
    A,

    /**
     * Continuing Education Unit
     * 
     */
    C,

    /**
     * Carnegie Units
     * 
     */
    G,

    /**
     * No Credit
     * 
     */
    N,

    /**
     * Quarter Hour Credit
     * 
     */
    Q,

    /**
     * Semester Hour Credit
     * 
     */
    S,

    /**
     * Units
     * 
     */
    U,

    /**
     * Vocational Credits
     * 
     */
    V,

    /**
     * Other Type of Credit
     * 
     */
    X;

    public String value() {
        return name();
    }

    public static AcademicCreditCodeType fromValue(String v) {
        return valueOf(v);
    }

}
