//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//


package com.portal.job.resumeparsing.xmlparsing.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompetencyWeightType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CompetencyWeightType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="levelOfInterest"/>
 *     &lt;enumeration value="skillLevel"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CompetencyWeightType")
@XmlEnum
public enum CompetencyWeightType {

    @XmlEnumValue("levelOfInterest")
    LEVEL_OF_INTEREST("levelOfInterest"),
    @XmlEnumValue("skillLevel")
    SKILL_LEVEL("skillLevel");
    private final String value;

    CompetencyWeightType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CompetencyWeightType fromValue(String v) {
        for (CompetencyWeightType c: CompetencyWeightType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
