//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//


package com.portal.job.resumeparsing.xmlparsing.model;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for EducationalMeasureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EducationalMeasureType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EducationalMeasure" type="{http://ns.hr-xml.org/2006-02-28}EducationMeasureType" minOccurs="0"/>
 *         &lt;element name="AcademicCreditCode" type="{http://ns.hr-xml.org/2006-02-28}AcademicCreditCodeType" minOccurs="0"/>
 *         &lt;element name="CourseLevelCode" type="{http://ns.hr-xml.org/2006-02-28}CourseLevelCodeType" minOccurs="0"/>
 *         &lt;element name="CumulativeSummaryIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AcademicCreditHoursIncluded" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="AcademicCreditHoursAttempted" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="AcademicCreditHoursEarned" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="ClassRank" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>integer">
 *                 &lt;attribute name="numberOfStudents" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="measureType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EducationalMeasureType", propOrder = {
    "educationalMeasure",
    "academicCreditCode",
    "courseLevelCode",
    "cumulativeSummaryIndicator",
    "academicCreditHoursIncluded",
    "academicCreditHoursAttempted",
    "academicCreditHoursEarned",
    "classRank"
})
public class EducationalMeasureType {

    @XmlElement(name = "EducationalMeasure")
    protected EducationMeasureType educationalMeasure;
    @XmlElement(name = "AcademicCreditCode")
    @XmlSchemaType(name = "string")
    protected AcademicCreditCodeType academicCreditCode;
    @XmlElement(name = "CourseLevelCode")
    protected String courseLevelCode;
    @XmlElement(name = "CumulativeSummaryIndicator")
    protected Boolean cumulativeSummaryIndicator;
    @XmlElement(name = "AcademicCreditHoursIncluded")
    protected BigDecimal academicCreditHoursIncluded;
    @XmlElement(name = "AcademicCreditHoursAttempted")
    protected BigDecimal academicCreditHoursAttempted;
    @XmlElement(name = "AcademicCreditHoursEarned")
    protected BigDecimal academicCreditHoursEarned;
    @XmlElement(name = "ClassRank")
    protected EducationalMeasureType.ClassRank classRank;
    @XmlAttribute(name = "measureType")
    protected String measureType;

    /**
     * Gets the value of the educationalMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link EducationMeasureType }
     *     
     */
    public EducationMeasureType getEducationalMeasure() {
        return educationalMeasure;
    }

    /**
     * Sets the value of the educationalMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link EducationMeasureType }
     *     
     */
    public void setEducationalMeasure(EducationMeasureType value) {
        this.educationalMeasure = value;
    }

    /**
     * Gets the value of the academicCreditCode property.
     * 
     * @return
     *     possible object is
     *     {@link AcademicCreditCodeType }
     *     
     */
    public AcademicCreditCodeType getAcademicCreditCode() {
        return academicCreditCode;
    }

    /**
     * Sets the value of the academicCreditCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcademicCreditCodeType }
     *     
     */
    public void setAcademicCreditCode(AcademicCreditCodeType value) {
        this.academicCreditCode = value;
    }

    /**
     * Gets the value of the courseLevelCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseLevelCode() {
        return courseLevelCode;
    }

    /**
     * Sets the value of the courseLevelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseLevelCode(String value) {
        this.courseLevelCode = value;
    }

    /**
     * Gets the value of the cumulativeSummaryIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCumulativeSummaryIndicator() {
        return cumulativeSummaryIndicator;
    }

    /**
     * Sets the value of the cumulativeSummaryIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCumulativeSummaryIndicator(Boolean value) {
        this.cumulativeSummaryIndicator = value;
    }

    /**
     * Gets the value of the academicCreditHoursIncluded property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAcademicCreditHoursIncluded() {
        return academicCreditHoursIncluded;
    }

    /**
     * Sets the value of the academicCreditHoursIncluded property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAcademicCreditHoursIncluded(BigDecimal value) {
        this.academicCreditHoursIncluded = value;
    }

    /**
     * Gets the value of the academicCreditHoursAttempted property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAcademicCreditHoursAttempted() {
        return academicCreditHoursAttempted;
    }

    /**
     * Sets the value of the academicCreditHoursAttempted property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAcademicCreditHoursAttempted(BigDecimal value) {
        this.academicCreditHoursAttempted = value;
    }

    /**
     * Gets the value of the academicCreditHoursEarned property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAcademicCreditHoursEarned() {
        return academicCreditHoursEarned;
    }

    /**
     * Sets the value of the academicCreditHoursEarned property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAcademicCreditHoursEarned(BigDecimal value) {
        this.academicCreditHoursEarned = value;
    }

    /**
     * Gets the value of the classRank property.
     * 
     * @return
     *     possible object is
     *     {@link EducationalMeasureType.ClassRank }
     *     
     */
    public EducationalMeasureType.ClassRank getClassRank() {
        return classRank;
    }

    /**
     * Sets the value of the classRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link EducationalMeasureType.ClassRank }
     *     
     */
    public void setClassRank(EducationalMeasureType.ClassRank value) {
        this.classRank = value;
    }

    /**
     * Gets the value of the measureType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasureType() {
        return measureType;
    }

    /**
     * Sets the value of the measureType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasureType(String value) {
        this.measureType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>integer">
     *       &lt;attribute name="numberOfStudents" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ClassRank {

        @XmlValue
        protected BigInteger value;
        @XmlAttribute(name = "numberOfStudents")
        protected BigInteger numberOfStudents;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setValue(BigInteger value) {
            this.value = value;
        }

        /**
         * Gets the value of the numberOfStudents property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumberOfStudents() {
            return numberOfStudents;
        }

        /**
         * Sets the value of the numberOfStudents property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumberOfStudents(BigInteger value) {
            this.numberOfStudents = value;
        }

    }

}
