//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//


package com.portal.job.resumeparsing.xmlparsing.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EmpContactInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmpContactInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ns.hr-xml.org/2006-02-28}PersonName" minOccurs="0"/>
 *         &lt;element name="ContactMethod" type="{http://ns.hr-xml.org/2006-02-28}ContactMethodType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LocationSummary" type="{http://ns.hr-xml.org/2006-02-28}EmploymentLocationSummaryType" minOccurs="0"/>
 *         &lt;element name="InternetDomainName" type="{http://ns.hr-xml.org/2006-02-28}InternetDomainNameType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="contactType" type="{http://ns.hr-xml.org/2006-02-28}ContactTypeStringExtensionType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmpContactInfoType", propOrder = {
    "personName",
    "contactMethod",
    "locationSummary",
    "internetDomainName"
})
public class EmpContactInfoType {

    @XmlElement(name = "PersonName")
    protected PersonNameType personName;
    @XmlElement(name = "ContactMethod")
    protected List<ContactMethodType> contactMethod;
    @XmlElement(name = "LocationSummary")
    protected EmploymentLocationSummaryType locationSummary;
    @XmlElement(name = "InternetDomainName")
    protected List<InternetDomainNameType> internetDomainName;
    @XmlAttribute(name = "contactType")
    protected String contactType;

    /**
     * Gets the value of the personName property.
     * 
     * @return
     *     possible object is
     *     {@link PersonNameType }
     *     
     */
    public PersonNameType getPersonName() {
        return personName;
    }

    /**
     * Sets the value of the personName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonNameType }
     *     
     */
    public void setPersonName(PersonNameType value) {
        this.personName = value;
    }

    /**
     * Gets the value of the contactMethod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactMethod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactMethod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactMethodType }
     * 
     * 
     */
    public List<ContactMethodType> getContactMethod() {
        if (contactMethod == null) {
            contactMethod = new ArrayList<ContactMethodType>();
        }
        return this.contactMethod;
    }

    /**
     * Gets the value of the locationSummary property.
     * 
     * @return
     *     possible object is
     *     {@link EmploymentLocationSummaryType }
     *     
     */
    public EmploymentLocationSummaryType getLocationSummary() {
        return locationSummary;
    }

    /**
     * Sets the value of the locationSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmploymentLocationSummaryType }
     *     
     */
    public void setLocationSummary(EmploymentLocationSummaryType value) {
        this.locationSummary = value;
    }

    /**
     * Gets the value of the internetDomainName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the internetDomainName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInternetDomainName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InternetDomainNameType }
     * 
     * 
     */
    public List<InternetDomainNameType> getInternetDomainName() {
        if (internetDomainName == null) {
            internetDomainName = new ArrayList<InternetDomainNameType>();
        }
        return this.internetDomainName;
    }

    /**
     * Gets the value of the contactType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactType() {
        return contactType;
    }

    /**
     * Sets the value of the contactType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactType(String value) {
        this.contactType = value;
    }

}
