//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//


package com.portal.job.resumeparsing.xmlparsing.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EmployerOrgDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmployerOrgDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EmployerOrgName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EmployerContactInfo" type="{http://ns.hr-xml.org/2006-02-28}EmpContactInfoType" minOccurs="0"/>
 *         &lt;element name="PositionHistory" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://ns.hr-xml.org/2006-02-28}PositionHistoryType">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://ns.hr-xml.org/2006-02-28}UserArea" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="employerOrgType" type="{http://ns.hr-xml.org/2006-02-28}EmpOrgTypeStringExtensionType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmployerOrgDataType", propOrder = {
    "employerOrgName",
    "employerContactInfo",
    "positionHistory",
    "userArea"
})
public class EmployerOrgDataType {

    @XmlElement(name = "EmployerOrgName", required = true)
    protected String employerOrgName;
    @XmlElement(name = "EmployerContactInfo")
    protected EmpContactInfoType employerContactInfo;
    @XmlElement(name = "PositionHistory", required = true)
    protected List<EmployerOrgDataType.PositionHistory> positionHistory;
    @XmlElement(name = "UserArea")
    protected UserAreaType userArea;
    @XmlAttribute(name = "employerOrgType")
    protected String employerOrgType;

    /**
     * Gets the value of the employerOrgName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployerOrgName() {
        return employerOrgName;
    }

    /**
     * Sets the value of the employerOrgName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployerOrgName(String value) {
        this.employerOrgName = value;
    }

    /**
     * Gets the value of the employerContactInfo property.
     * 
     * @return
     *     possible object is
     *     {@link EmpContactInfoType }
     *     
     */
    public EmpContactInfoType getEmployerContactInfo() {
        return employerContactInfo;
    }

    /**
     * Sets the value of the employerContactInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmpContactInfoType }
     *     
     */
    public void setEmployerContactInfo(EmpContactInfoType value) {
        this.employerContactInfo = value;
    }

    /**
     * Gets the value of the positionHistory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the positionHistory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPositionHistory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EmployerOrgDataType.PositionHistory }
     * 
     * 
     */
    public List<EmployerOrgDataType.PositionHistory> getPositionHistory() {
        if (positionHistory == null) {
            positionHistory = new ArrayList<EmployerOrgDataType.PositionHistory>();
        }
        return this.positionHistory;
    }

    /**
     * Gets the value of the userArea property.
     * 
     * @return
     *     possible object is
     *     {@link UserAreaType }
     *     
     */
    public UserAreaType getUserArea() {
        return userArea;
    }

    /**
     * Sets the value of the userArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserAreaType }
     *     
     */
    public void setUserArea(UserAreaType value) {
        this.userArea = value;
    }

    /**
     * Gets the value of the employerOrgType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployerOrgType() {
        return employerOrgType;
    }

    /**
     * Sets the value of the employerOrgType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployerOrgType(String value) {
        this.employerOrgType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://ns.hr-xml.org/2006-02-28}PositionHistoryType">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PositionHistory
        extends PositionHistoryType
    {


    }

}
