//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//


package com.portal.job.resumeparsing.xmlparsing.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for organizationTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="organizationTypes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="department"/>
 *     &lt;enumeration value="group"/>
 *     &lt;enumeration value="team"/>
 *     &lt;enumeration value="branch"/>
 *     &lt;enumeration value="company"/>
 *     &lt;enumeration value="subsidiary"/>
 *     &lt;enumeration value="unit"/>
 *     &lt;enumeration value="headquarters"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "organizationTypes")
@XmlEnum
public enum OrganizationTypes {

    @XmlEnumValue("department")
    DEPARTMENT("department"),
    @XmlEnumValue("group")
    GROUP("group"),
    @XmlEnumValue("team")
    TEAM("team"),
    @XmlEnumValue("branch")
    BRANCH("branch"),
    @XmlEnumValue("company")
    COMPANY("company"),
    @XmlEnumValue("subsidiary")
    SUBSIDIARY("subsidiary"),
    @XmlEnumValue("unit")
    UNIT("unit"),
    @XmlEnumValue("headquarters")
    HEADQUARTERS("headquarters");
    private final String value;

    OrganizationTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OrganizationTypes fromValue(String v) {
        for (OrganizationTypes c: OrganizationTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
