//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ns.hr-xml.org/2006-02-28", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.portal.job.resumeparsing.xmlparsing.model;
