//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//


package com.portal.job.resumeparsing.xmlparsing.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PatentStatusTypeTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PatentStatusTypeTypes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PatentIssued"/>
 *     &lt;enumeration value="PatentPending"/>
 *     &lt;enumeration value="PatentFiled"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PatentStatusTypeTypes")
@XmlEnum
public enum PatentStatusTypeTypes {

    @XmlEnumValue("PatentIssued")
    PATENT_ISSUED("PatentIssued"),
    @XmlEnumValue("PatentPending")
    PATENT_PENDING("PatentPending"),
    @XmlEnumValue("PatentFiled")
    PATENT_FILED("PatentFiled");
    private final String value;

    PatentStatusTypeTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PatentStatusTypeTypes fromValue(String v) {
        for (PatentStatusTypeTypes c: PatentStatusTypeTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
