//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//


package com.portal.job.resumeparsing.xmlparsing.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for positionTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="positionTypes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="directHire"/>
 *     &lt;enumeration value="contract"/>
 *     &lt;enumeration value="temp"/>
 *     &lt;enumeration value="contractToHire"/>
 *     &lt;enumeration value="tempToHire"/>
 *     &lt;enumeration value="volunteer"/>
 *     &lt;enumeration value="internship"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "positionTypes")
@XmlEnum
public enum PositionTypes {

    @XmlEnumValue("directHire")
    DIRECT_HIRE("directHire"),
    @XmlEnumValue("contract")
    CONTRACT("contract"),
    @XmlEnumValue("temp")
    TEMP("temp"),
    @XmlEnumValue("contractToHire")
    CONTRACT_TO_HIRE("contractToHire"),
    @XmlEnumValue("tempToHire")
    TEMP_TO_HIRE("tempToHire"),
    @XmlEnumValue("volunteer")
    VOLUNTEER("volunteer"),
    @XmlEnumValue("internship")
    INTERNSHIP("internship");
    private final String value;

    PositionTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PositionTypes fromValue(String v) {
        for (PositionTypes c: PositionTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
