//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//


package com.portal.job.resumeparsing.xmlparsing.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResumeId" type="{http://ns.hr-xml.org/2006-02-28}EntityIdType" minOccurs="0"/>
 *         &lt;element name="DistributionGuidelines" type="{http://ns.hr-xml.org/2006-02-28}DistributionGuidelinesType" minOccurs="0"/>
 *         &lt;element ref="{http://ns.hr-xml.org/2006-02-28}StructuredXMLResume" minOccurs="0"/>
 *         &lt;element ref="{http://ns.hr-xml.org/2006-02-28}NonXMLResume" minOccurs="0"/>
 *         &lt;element ref="{http://ns.hr-xml.org/2006-02-28}UserArea" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "resumeId",
    "distributionGuidelines",
    "structuredXMLResume",
    "nonXMLResume",
    "userArea"
})
@XmlRootElement(name = "Resume")
public class Resume {

    @XmlElement(name = "ResumeId")
    protected EntityIdType resumeId;
    @XmlElement(name = "DistributionGuidelines")
    protected DistributionGuidelinesType distributionGuidelines;
    @XmlElement(name = "StructuredXMLResume")
    protected StructuredXMLResumeType structuredXMLResume;
    @XmlElement(name = "NonXMLResume")
    protected NonXMLResumeType nonXMLResume;
    @XmlElement(name = "UserArea")
    protected UserAreaType userArea;

    /**
     * Gets the value of the resumeId property.
     * 
     * @return
     *     possible object is
     *     {@link EntityIdType }
     *     
     */
    public EntityIdType getResumeId() {
        return resumeId;
    }

    /**
     * Sets the value of the resumeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityIdType }
     *     
     */
    public void setResumeId(EntityIdType value) {
        this.resumeId = value;
    }

    /**
     * Gets the value of the distributionGuidelines property.
     * 
     * @return
     *     possible object is
     *     {@link DistributionGuidelinesType }
     *     
     */
    public DistributionGuidelinesType getDistributionGuidelines() {
        return distributionGuidelines;
    }

    /**
     * Sets the value of the distributionGuidelines property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistributionGuidelinesType }
     *     
     */
    public void setDistributionGuidelines(DistributionGuidelinesType value) {
        this.distributionGuidelines = value;
    }

    /**
     * Gets the value of the structuredXMLResume property.
     * 
     * @return
     *     possible object is
     *     {@link StructuredXMLResumeType }
     *     
     */
    public StructuredXMLResumeType getStructuredXMLResume() {
        return structuredXMLResume;
    }

    /**
     * Sets the value of the structuredXMLResume property.
     * 
     * @param value
     *     allowed object is
     *     {@link StructuredXMLResumeType }
     *     
     */
    public void setStructuredXMLResume(StructuredXMLResumeType value) {
        this.structuredXMLResume = value;
    }

    /**
     * Gets the value of the nonXMLResume property.
     * 
     * @return
     *     possible object is
     *     {@link NonXMLResumeType }
     *     
     */
    public NonXMLResumeType getNonXMLResume() {
        return nonXMLResume;
    }

    /**
     * Sets the value of the nonXMLResume property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonXMLResumeType }
     *     
     */
    public void setNonXMLResume(NonXMLResumeType value) {
        this.nonXMLResume = value;
    }

    /**
     * Gets the value of the userArea property.
     * 
     * @return
     *     possible object is
     *     {@link UserAreaType }
     *     
     */
    public UserAreaType getUserArea() {
        return userArea;
    }

    /**
     * Sets the value of the userArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserAreaType }
     *     
     */
    public void setUserArea(UserAreaType value) {
        this.userArea = value;
    }

}
