//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//


package com.portal.job.resumeparsing.xmlparsing.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResumeItemTypeTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ResumeItemTypeTypes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Activities"/>
 *     &lt;enumeration value="Interests"/>
 *     &lt;enumeration value="Personal"/>
 *     &lt;enumeration value="Community"/>
 *     &lt;enumeration value="Hobbies"/>
 *     &lt;enumeration value="Volunteer"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ResumeItemTypeTypes")
@XmlEnum
public enum ResumeItemTypeTypes {

    @XmlEnumValue("Activities")
    ACTIVITIES("Activities"),
    @XmlEnumValue("Interests")
    INTERESTS("Interests"),
    @XmlEnumValue("Personal")
    PERSONAL("Personal"),
    @XmlEnumValue("Community")
    COMMUNITY("Community"),
    @XmlEnumValue("Hobbies")
    HOBBIES("Hobbies"),
    @XmlEnumValue("Volunteer")
    VOLUNTEER("Volunteer");
    private final String value;

    ResumeItemTypeTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ResumeItemTypeTypes fromValue(String v) {
        for (ResumeItemTypeTypes c: ResumeItemTypeTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
