//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//


package com.portal.job.resumeparsing.xmlparsing.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SchoolTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SchoolTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="current"/>
 *     &lt;enumeration value="prior"/>
 *     &lt;enumeration value="joint"/>
 *     &lt;enumeration value="degree"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SchoolTypeType")
@XmlEnum
public enum SchoolTypeType {

    @XmlEnumValue("current")
    CURRENT("current"),
    @XmlEnumValue("prior")
    PRIOR("prior"),
    @XmlEnumValue("joint")
    JOINT("joint"),
    @XmlEnumValue("degree")
    DEGREE("degree");
    private final String value;

    SchoolTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SchoolTypeType fromValue(String v) {
        for (SchoolTypeType c: SchoolTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
