//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//


package com.portal.job.resumeparsing.xmlparsing.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SchoolDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SchoolDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InternetDomainName" type="{http://ns.hr-xml.org/2006-02-28}InternetDomainNameType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SchoolId" type="{http://ns.hr-xml.org/2006-02-28}EntityIdType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SchoolName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://ns.hr-xml.org/2006-02-28}SchoolTypeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SchoolDataType", propOrder = {
    "internetDomainName",
    "schoolId",
    "schoolName"
})
public class SchoolDataType {

    @XmlElement(name = "InternetDomainName")
    protected List<InternetDomainNameType> internetDomainName;
    @XmlElement(name = "SchoolId")
    protected List<EntityIdType> schoolId;
    @XmlElement(name = "SchoolName")
    protected String schoolName;
    @XmlAttribute(name = "type")
    protected SchoolTypeType type;

    /**
     * Gets the value of the internetDomainName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the internetDomainName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInternetDomainName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InternetDomainNameType }
     * 
     * 
     */
    public List<InternetDomainNameType> getInternetDomainName() {
        if (internetDomainName == null) {
            internetDomainName = new ArrayList<InternetDomainNameType>();
        }
        return this.internetDomainName;
    }

    /**
     * Gets the value of the schoolId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the schoolId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSchoolId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityIdType }
     * 
     * 
     */
    public List<EntityIdType> getSchoolId() {
        if (schoolId == null) {
            schoolId = new ArrayList<EntityIdType>();
        }
        return this.schoolId;
    }

    /**
     * Gets the value of the schoolName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * Sets the value of the schoolName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchoolName(String value) {
        this.schoolName = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link SchoolTypeType }
     *     
     */
    public SchoolTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchoolTypeType }
     *     
     */
    public void setType(SchoolTypeType value) {
        this.type = value;
    }

}
