//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.23 at 05:06:12 PM IST 
//


package com.portal.job.resumeparsing.xmlparsing.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpeakingTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SpeakingTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="speech"/>
 *     &lt;enumeration value="presentation"/>
 *     &lt;enumeration value="demonstration"/>
 *     &lt;enumeration value="interview"/>
 *     &lt;enumeration value="debate"/>
 *     &lt;enumeration value="panel discussion"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SpeakingTypeType")
@XmlEnum
public enum SpeakingTypeType {

    @XmlEnumValue("speech")
    SPEECH("speech"),
    @XmlEnumValue("presentation")
    PRESENTATION("presentation"),
    @XmlEnumValue("demonstration")
    DEMONSTRATION("demonstration"),
    @XmlEnumValue("interview")
    INTERVIEW("interview"),
    @XmlEnumValue("debate")
    DEBATE("debate"),
    @XmlEnumValue("panel discussion")
    PANEL_DISCUSSION("panel discussion");
    private final String value;

    SpeakingTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SpeakingTypeType fromValue(String v) {
        for (SpeakingTypeType c: SpeakingTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
